[project]
name = "etl-craft"
version = "0.1.0"
description = "Standalone, metadata-driven ETL orchestration engine"
readme = "README.md"
authors = [
    { name = "venkatcg00", email = "venkatcg0@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
etl-craft = "etl_craft:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
