-- The cross-pipeline trackers become an append-only log of every upstream run consumed.

-- Every upstream run a downstream consumed, one row each, never updated: for a dependency on a
-- pipeline, the downstream run and the upstream run; for a dependency on another pipeline's task,
-- the downstream task and the upstream task run. A dependency's latest row is what it last
-- consumed: an upstream run satisfies it only when it is newer than that one. PIPELINE_RUN_ID is
-- NULL on the rows carried over from the trackers this table replaced.
CREATE TABLE AUD_DEPENDENCY_CONSUMPTION (
    CONSUMPTION_ID            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PIPELINE_DEPENDENCY_ID    BIGINT REFERENCES CFG_PIPELINE_DEPENDENCY(PIPELINE_DEPENDENCY_ID),
    TASK_DEPENDENCY_ID        BIGINT REFERENCES CFG_TASK_DEPENDENCY(TASK_DEPENDENCY_ID),
    PIPELINE_ID               BIGINT NOT NULL REFERENCES CFG_PIPELINES(PIPELINE_ID),
    PIPELINE_RUN_ID           BIGINT REFERENCES AUD_PIPELINES_RUN_LOG(PIPELINE_RUN_ID),
    TASK_ID                   BIGINT REFERENCES CFG_TASKS(TASK_ID),
    DEPENDS_ON_PIPELINE_ID    BIGINT NOT NULL REFERENCES CFG_PIPELINES(PIPELINE_ID),
    CONSUMED_PIPELINE_RUN_ID  BIGINT NOT NULL REFERENCES AUD_PIPELINES_RUN_LOG(PIPELINE_RUN_ID),
    CONSUMED_TASK_RUN_ID      BIGINT REFERENCES AUD_TASK_RUN_LOG(TASK_RUN_ID),
    CONSUMED_AT               TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_consumption_one_dependency CHECK (
        (PIPELINE_DEPENDENCY_ID IS NULL) <> (TASK_DEPENDENCY_ID IS NULL)
    )
);

CREATE INDEX ix_consumption_pipeline_dependency
    ON AUD_DEPENDENCY_CONSUMPTION (PIPELINE_DEPENDENCY_ID, CONSUMPTION_ID);
CREATE INDEX ix_consumption_task_dependency
    ON AUD_DEPENDENCY_CONSUMPTION (TASK_DEPENDENCY_ID, CONSUMPTION_ID);
CREATE INDEX ix_consumption_run ON AUD_DEPENDENCY_CONSUMPTION (PIPELINE_RUN_ID);

-- The trackers' last consumed runs become the log's first rows.
INSERT INTO AUD_DEPENDENCY_CONSUMPTION (PIPELINE_DEPENDENCY_ID, PIPELINE_ID, DEPENDS_ON_PIPELINE_ID,
                                        CONSUMED_PIPELINE_RUN_ID, CONSUMED_AT)
SELECT PIPELINE_DEPENDENCY_ID, PIPELINE_ID, DEPENDS_ON_PIPELINE_ID, LAST_CONSUMED_PIPELINE_RUN_ID,
       LAST_UPDATED_TIMESTAMP
FROM AUD_PIPELINE_DEPENDENCY_TRACKER
WHERE LAST_CONSUMED_PIPELINE_RUN_ID IS NOT NULL;

INSERT INTO AUD_DEPENDENCY_CONSUMPTION (TASK_DEPENDENCY_ID, PIPELINE_ID, TASK_ID,
                                        DEPENDS_ON_PIPELINE_ID, CONSUMED_PIPELINE_RUN_ID,
                                        CONSUMED_TASK_RUN_ID, CONSUMED_AT)
SELECT t.TASK_DEPENDENCY_ID, t.PIPELINE_ID, t.TASK_ID, t.DEPENDS_ON_PIPELINE_ID, r.PIPELINE_RUN_ID,
       t.LAST_CONSUMED_TASK_RUN_ID, t.LAST_UPDATED_TIMESTAMP
FROM AUD_TASK_DEPENDENCY_TRACKER t
JOIN AUD_TASK_RUN_LOG r ON r.TASK_RUN_ID = t.LAST_CONSUMED_TASK_RUN_ID;

DROP TABLE AUD_PIPELINE_DEPENDENCY_TRACKER;
DROP TABLE AUD_TASK_DEPENDENCY_TRACKER;

COMMENT ON TABLE CFG_PIPELINE_DEPENDENCY IS 'A pipeline waits for another pipeline''s outcome. Checked against AUD_DEPENDENCY_CONSUMPTION when the pipeline starts.';
COMMENT ON TABLE CFG_TASK_DEPENDENCY IS 'A task waits for another task''s outcome. Same-pipeline dependencies order the pipeline''s waves; one on another pipeline''s task is checked against AUD_DEPENDENCY_CONSUMPTION when the task starts.';
