-- Give historical runs a stable identity without changing their ids.
ALTER TABLE AUD_PIPELINES_RUN_LOG ADD COLUMN RUN_KEY          VARCHAR DEFAULT ('manual:' || gen_random_uuid()::text);
ALTER TABLE AUD_PIPELINES_RUN_LOG ADD COLUMN TRIGGER_KIND     VARCHAR DEFAULT 'MANUAL';
ALTER TABLE AUD_PIPELINES_RUN_LOG ADD COLUMN OWNER_ID         VARCHAR;
ALTER TABLE AUD_PIPELINES_RUN_LOG ADD COLUMN LEASE_EXPIRES_AT TIMESTAMPTZ;
ALTER TABLE AUD_PIPELINES_RUN_LOG ADD COLUMN OUTPUT_REVISION  INT DEFAULT 1;
ALTER TABLE AUD_PIPELINES_RUN_LOG ADD COLUMN CONFIG_SHA256    VARCHAR(64);
UPDATE AUD_PIPELINES_RUN_LOG SET RUN_KEY='legacy:' || PIPELINE_RUN_ID, TRIGGER_KIND=CASE WHEN BACKFILL='Y' THEN 'BACKFILL' ELSE 'MANUAL' END;
ALTER TABLE AUD_PIPELINES_RUN_LOG ALTER COLUMN RUN_KEY SET NOT NULL;
ALTER TABLE AUD_PIPELINES_RUN_LOG ALTER COLUMN TRIGGER_KIND SET NOT NULL;
ALTER TABLE AUD_PIPELINES_RUN_LOG ALTER COLUMN OUTPUT_REVISION SET NOT NULL;
ALTER TABLE AUD_PIPELINES_RUN_LOG ADD CONSTRAINT ck_pipeline_run_trigger_kind CHECK (TRIGGER_KIND IN ('SCHEDULE','MANUAL','BACKFILL','ORCHESTRATOR','STAND_IN'));
CREATE UNIQUE INDEX ux_pipeline_run_key ON AUD_PIPELINES_RUN_LOG (PIPELINE_ID, RUN_KEY);
ALTER TABLE CFG_PIPELINE_DEPENDENCY ADD COLUMN CONSUME_REPAIRS         VARCHAR(1) NOT NULL DEFAULT 'Y' CONSTRAINT ck_pipedep_consume_repairs CHECK (CONSUME_REPAIRS IN ('Y','N'));
ALTER TABLE CFG_TASK_DEPENDENCY ADD COLUMN CONSUME_REPAIRS         VARCHAR(1) NOT NULL DEFAULT 'Y' CONSTRAINT ck_taskdep_consume_repairs CHECK (CONSUME_REPAIRS IN ('Y','N'));
ALTER TABLE AUD_DEPENDENCY_CONSUMPTION ADD COLUMN CONSUMED_REVISION INT NOT NULL DEFAULT 1;

-- Attempt history and the dependencies judged at admission.
CREATE TABLE AUD_TASK_ATTEMPTS (
    ATTEMPT_ID       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TASK_RUN_ID      BIGINT NOT NULL REFERENCES AUD_TASK_RUN_LOG(TASK_RUN_ID),
    ATTEMPT_NUMBER   INT NOT NULL,
    STATUS           VARCHAR NOT NULL,
    OWNER_ID         VARCHAR,
    LEASE_EXPIRES_AT TIMESTAMPTZ,
    HEARTBEAT_AT     TIMESTAMPTZ,
    QUEUED_AT        TIMESTAMPTZ,
    CLAIMED_AT       TIMESTAMPTZ,
    STARTED_AT       TIMESTAMPTZ,
    ENDED_AT         TIMESTAMPTZ,
    HOST             VARCHAR,
    PID              INT,
    PROCESS_START    VARCHAR,
    EXIT_CODE        INT,
    SOURCE_COUNT     BIGINT,
    TARGET_COUNT     BIGINT,
    INSERT_COUNT     BIGINT,
    UPDATE_COUNT     BIGINT,
    DELETE_COUNT     BIGINT,
    ROWS_WRITTEN     BIGINT,
    ERROR_MESSAGE    VARCHAR,
    TASK_LOG         VARCHAR,
    LOG_PATH         VARCHAR,
    REQUESTED_BY     VARCHAR,
    CONSTRAINT ck_attempt_status CHECK (STATUS IN ('QUEUED','CLAIMED','RUNNING','SUCCESS','FAILED','TIMED_OUT','CANCELLED','LOST'))
);
CREATE UNIQUE INDEX ux_attempt_number ON AUD_TASK_ATTEMPTS (TASK_RUN_ID, ATTEMPT_NUMBER);
CREATE UNIQUE INDEX ux_attempt_one_active ON AUD_TASK_ATTEMPTS (TASK_RUN_ID)
    WHERE STATUS IN ('QUEUED','CLAIMED','RUNNING');
CREATE INDEX ix_attempt_status_lease ON AUD_TASK_ATTEMPTS (STATUS, LEASE_EXPIRES_AT);

-- Each dependency judged at admission, with the selected upstream revision and reason.
CREATE TABLE AUD_GATE_DECISIONS (
    DECISION_ID              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PIPELINE_RUN_ID          BIGINT NOT NULL REFERENCES AUD_PIPELINES_RUN_LOG(PIPELINE_RUN_ID),
    ATTEMPT_ID               BIGINT REFERENCES AUD_TASK_ATTEMPTS(ATTEMPT_ID),
    PIPELINE_DEPENDENCY_ID   BIGINT REFERENCES CFG_PIPELINE_DEPENDENCY(PIPELINE_DEPENDENCY_ID),
    TASK_DEPENDENCY_ID       BIGINT REFERENCES CFG_TASK_DEPENDENCY(TASK_DEPENDENCY_ID),
    SELECTED_PIPELINE_RUN_ID BIGINT REFERENCES AUD_PIPELINES_RUN_LOG(PIPELINE_RUN_ID),
    SELECTED_TASK_RUN_ID     BIGINT REFERENCES AUD_TASK_RUN_LOG(TASK_RUN_ID),
    SELECTED_REVISION        INT,
    RESULT                   VARCHAR NOT NULL,
    REASON                   VARCHAR NOT NULL,
    DECIDED_AT               TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_gate_one_dependency CHECK (
        (PIPELINE_DEPENDENCY_ID IS NOT NULL AND TASK_DEPENDENCY_ID IS NULL)
        OR (PIPELINE_DEPENDENCY_ID IS NULL AND TASK_DEPENDENCY_ID IS NOT NULL)
    ),
    CONSTRAINT ck_gate_result CHECK (RESULT IN ('SATISFIED','UNSATISFIED','BYPASSED'))
);

-- Skipped tasks have no execution attempt; their summary retains the gate outcome.
INSERT INTO AUD_TASK_ATTEMPTS (
    TASK_RUN_ID, ATTEMPT_NUMBER, STATUS, STARTED_AT, ENDED_AT,
    SOURCE_COUNT, TARGET_COUNT, INSERT_COUNT, UPDATE_COUNT, DELETE_COUNT,
    ROWS_WRITTEN, ERROR_MESSAGE, TASK_LOG
)
SELECT TASK_RUN_ID, ATTEMPT_COUNT,
       CASE WHEN STATUS = 'IN-PROGRESS' THEN 'RUNNING' ELSE STATUS END,
       START_DATE, END_DATE, SOURCE_COUNT, TARGET_COUNT, INSERT_COUNT, UPDATE_COUNT,
       DELETE_COUNT, ROWS_WRITTEN, ERROR_MESSAGE, TASK_LOG
FROM AUD_TASK_RUN_LOG WHERE STATUS <> 'SKIPPED';
