CREATE TABLE AUD_TARGET_HASH_VERSION (
    TARGET_OBJECT VARCHAR PRIMARY KEY,
    HASH_VERSION INTEGER NOT NULL CONSTRAINT ck_target_hash_version CHECK (HASH_VERSION IN (1,2)),
    RECOMPUTED_AT TIMESTAMPTZ NOT NULL
);

CREATE TRIGGER trg_actor_guard_aud_target_hash_version BEFORE INSERT OR UPDATE OR DELETE ON AUD_TARGET_HASH_VERSION FOR EACH ROW EXECUTE FUNCTION etl_craft_guard();
CREATE TRIGGER trg_truncate_aud_target_hash_version BEFORE TRUNCATE ON AUD_TARGET_HASH_VERSION FOR EACH STATEMENT EXECUTE FUNCTION etl_craft_guard();
