-- Persist schedule policies and allow pending scheduled runs.
ALTER TABLE CFG_PIPELINES ADD COLUMN SCHEDULE_TIMEZONE VARCHAR;
ALTER TABLE CFG_PIPELINES ADD COLUMN CATCHUP VARCHAR(1) NOT NULL DEFAULT 'N' CONSTRAINT ck_schedule_catchup CHECK (CATCHUP IN ('Y','N'));
ALTER TABLE CFG_PIPELINES ADD COLUMN MAX_CATCHUP_RUNS INT NOT NULL DEFAULT 1 CONSTRAINT ck_schedule_catchup_runs CHECK (MAX_CATCHUP_RUNS > 0);
ALTER TABLE CFG_PIPELINES ADD COLUMN OVERLAP_POLICY VARCHAR NOT NULL DEFAULT 'SKIP' CONSTRAINT ck_schedule_overlap CHECK (OVERLAP_POLICY IN ('SKIP','QUEUE'));
ALTER TABLE CFG_PIPELINES ADD COLUMN SCHEDULE_START_DATE DATE;
ALTER TABLE AUD_PIPELINES_RUN_LOG DROP CONSTRAINT ck_pipeline_run_status;
ALTER TABLE AUD_PIPELINES_RUN_LOG ADD CONSTRAINT ck_pipeline_run_status CHECK (STATUS IN ('QUEUED','IN-PROGRESS','SUCCESS','FAILED','SKIPPED','CANCELLED'));
CREATE INDEX ix_pipeline_schedule_key ON AUD_PIPELINES_RUN_LOG (PIPELINE_ID, RUN_KEY) WHERE TRIGGER_KIND = 'SCHEDULE';
