-- Durable gate polling budget; TASK_ID is NULL for pipeline admission and NEXT_CHECK_AT is NULL when settled.
CREATE TABLE AUD_GATE_WAITS (
    PIPELINE_RUN_ID BIGINT NOT NULL REFERENCES AUD_PIPELINES_RUN_LOG(PIPELINE_RUN_ID),
    TASK_ID BIGINT REFERENCES CFG_TASKS(TASK_ID),
    FIRST_CHECK_AT TIMESTAMPTZ NOT NULL,
    NEXT_CHECK_AT TIMESTAMPTZ,
    LOOKS INT NOT NULL,
    WAIT_UNTIL TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_gate_wait_task CHECK (TASK_ID IS NULL OR TASK_ID > 0),
    CONSTRAINT ck_gate_wait_looks CHECK (LOOKS >= 0 AND LOOKS <= 30)
);
CREATE UNIQUE INDEX ux_gate_wait ON AUD_GATE_WAITS (PIPELINE_RUN_ID, COALESCE(TASK_ID,0));
CREATE TRIGGER trg_actor_guard_aud_gate_waits BEFORE INSERT OR UPDATE OR DELETE
ON AUD_GATE_WAITS FOR EACH ROW EXECUTE FUNCTION etl_craft_guard();
CREATE TRIGGER trg_truncate_aud_gate_waits BEFORE TRUNCATE ON AUD_GATE_WAITS
FOR EACH STATEMENT EXECUTE FUNCTION etl_craft_guard();
