CREATE TABLE CFG_API_TOKENS (
    TOKEN_ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL,
    TOKEN_SHA256 VARCHAR(64) NOT NULL UNIQUE,
    ROLE VARCHAR(16) NOT NULL CHECK (ROLE IN ('viewer', 'operator', 'admin')),
    PROJECT_ID BIGINT,
    CREATED_BY VARCHAR(128) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP,
    REVOKED_AT TIMESTAMP
);

COMMENT ON TABLE CFG_API_TOKENS IS 'Opaque API credentials: SHA-256 hashes, roles and expiry; token values are never stored or cloned.';
