CREATE TABLE AUD_TARGET_VIEW_STATEMENT (
    TARGET_OBJECT VARCHAR PRIMARY KEY,
    STATEMENT_SHA256 VARCHAR(64) NOT NULL,
    RECORDED_AT TIMESTAMPTZ NOT NULL
);

CREATE TRIGGER trg_actor_guard_aud_target_view_statement BEFORE INSERT OR UPDATE OR DELETE ON AUD_TARGET_VIEW_STATEMENT FOR EACH ROW EXECUTE FUNCTION etl_craft_guard();
CREATE TRIGGER trg_truncate_aud_target_view_statement BEFORE TRUNCATE ON AUD_TARGET_VIEW_STATEMENT FOR EACH STATEMENT EXECUTE FUNCTION etl_craft_guard();
