"""``generate-yml``: a pipeline's DAG, or the global trigger DAG, as YAML for an orchestrator.

A pipeline's DAG has one task per active task, which runs ``etl-craft run --task_code``, between
an ``__init__`` task (``--init-only``) and a ``__finalize__`` task (``--finalize-only``) that runs
whatever happened. Each task carries one Airflow ``trigger_rule``, worked out from its run
condition and its dependencies' types. Only one run of the DAG goes at a time
(``max_active_runs: 1``), as only one run of a pipeline is ``IN-PROGRESS``.

In remote mode the DAG holds every scheduling rule, since the engine checks none (see
``execution.remote``): a dependency on another pipeline's task is a sensor step before the task,
and a dependency on another pipeline is a sensor step after ``__init__`` and before the tasks,
unless ``Global_dag`` is on and the global DAG triggers the pipelines in order. Rules the
orchestrator does not support raise ``RemoteUnsupportedError``.

In local mode the engine checks every rule itself when the run or the task starts. Where Airflow
has no exact rule (``N``, ``HAS_DATA``, or dependencies of mixed types) the permissive
``all_done`` is written, and the engine records the task ``SKIPPED`` if its condition is not met;
dependencies on other pipelines are listed for information.

The DAG's settings come from the pipeline's ``PIPELINE_PARAMETERS``, then Orchestration's DAG
defaults, then a built-in default.
"""

from __future__ import annotations

from typing import Any, TypeVar

import yaml
from sqlalchemy.engine import Connection

from etl_craft.config import ConnectorConfig
from etl_craft.core.enums import Mode
from etl_craft.core.errors import ConfigurationError, GraphError
from etl_craft.core.graph import build_graph
from etl_craft.engine.queries import statement
from etl_craft.engine.repository.dependencies import (
    fetch_cross_pipeline_task_edges,
    fetch_pipeline_dependency_edges,
    fetch_pipeline_graph,
)
from etl_craft.engine.repository.pipelines import (
    PipelineDetail,
    fetch_pipeline_detail,
    resolve_pipeline_id,
)
from etl_craft.engine.repository.tasks import fetch_task_codes
from etl_craft.execution.remote import (
    DAG_SENSOR_STATES,
    SENSOR_TYPE,
    TASK_SENSOR_STATES,
    require_supported,
)

T = TypeVar("T")

INIT_TASK = "__init__"
FINALIZE_TASK = "__finalize__"
GLOBAL_DAG_ID = "etl_craft_global_orchestration"
DOCS_DAG_ID = "etl_craft_docs"
DOCS_TASK = "generate_docs"
RUN_DATE_TEMPLATE = "{{ data_interval_end | ds }}"
"""How a remote DAG's ``__init__`` passes the run's date: Airflow's end of the data interval,
the day a scheduled run fires, so ``$$run_date`` means the same as in local mode, and a backfill
by the orchestrator runs each day as of its own date."""

DEFAULT_RETRIES = 1
DEFAULT_RETRY_DELAY_MINUTES = 5

HEADER = """\
# Generated by `etl-craft generate-yml`. Do not edit by hand; generate it again.
#
# Local mode: etl-craft checks every rule itself when a run or a task starts.
#
# `tasks:` is what the orchestrator runs. Each task has one `trigger_rule`, worked out
# from its RUN_CONDITION and its dependencies' DEPENDENCY_TYPE. Where Airflow has no
# exact rule (RUN_CONDITION N, HAS_DATA, or dependencies of mixed types) it is
# `all_done`, and etl-craft decides when the task runs, recording it SKIPPED if its
# condition is not met.
#
# `pipeline_dependencies:` and `cross_pipeline_task_dependencies:` are for reading
# only: etl-craft checks them itself when the run or the task starts.
"""

REMOTE_HEADER = """\
# Generated by `etl-craft generate-yml`. Do not edit by hand; generate it again.
#
# Remote mode: this DAG is the only source of truth for scheduling. etl-craft runs
# each task when told to and checks none of these rules itself.
#
# `tasks:` is what the orchestrator runs. `__init__` passes the run's date as
# `--run-date {{ data_interval_end | ds }}`, an Airflow template: with another
# orchestrator, pass its own date for the run. Each task has one `trigger_rule`, worked
# out from its RUN_CONDITION and its dependencies' DEPENDENCY_TYPE. A step with `sensor:`
# waits for another DAG (`external_task_id: null`) or one of its tasks: it succeeds
# once the upstream is in one of `allowed_states`, and fails once it is in one of
# `failed_states`. Point it at the upstream run it should judge (for Airflow's
# ExternalTaskSensor, with `execution_delta` or `execution_date_fn` when the two
# DAGs' schedules differ).
"""

TRIGGER_RULES: dict[tuple[str, str], str] = {
    ("ALL", "SUCCESS"): "all_success",
    ("ALL", "FAILURE"): "all_failed",
    ("ALL", "ALWAYS"): "all_done",
    ("ALL", "HAS_DATA"): "all_success",
    ("ANY", "SUCCESS"): "one_success",
    ("ANY", "FAILURE"): "one_failed",
    ("ANY", "ALWAYS"): "one_done",
    ("ANY", "HAS_DATA"): "one_success",
}
"""The Airflow trigger rule for a run condition and a dependency type; ``N`` is ``all_done``."""


def trigger_rule(run_condition: str, dependency_types: list[str]) -> str:
    """Return one trigger rule for a task from its run condition and its dependencies' types."""
    distinct = set(dependency_types)
    if not distinct:
        return "all_success"
    if len(distinct) > 1 or run_condition == "N":
        return "all_done"
    kind = distinct.pop()
    try:
        return TRIGGER_RULES[(run_condition, kind)]
    except KeyError:
        raise GraphError(
            f"no trigger rule for RUN_CONDITION={run_condition!r} and DEPENDENCY_TYPE={kind!r}"
        ) from None


def _first(*values: T | None) -> T | None:
    return next((value for value in values if value is not None), None)


def pipeline_dag(conn: Connection, config: ConnectorConfig, pipeline_code: str) -> dict[str, Any]:
    """Return the DAG of ``pipeline_code`` as a dict, in the order it is written.

    Raises ``RemoteUnsupportedError`` in remote mode for rules the orchestrator does not support.
    """
    if config.mode == Mode.REMOTE:
        return _remote_pipeline_dag(conn, config, pipeline_code)
    pipeline_id = resolve_pipeline_id(conn, pipeline_code)
    detail = fetch_pipeline_detail(conn, pipeline_id)
    data = fetch_pipeline_graph(conn, pipeline_id)
    codes = fetch_task_codes(conn, pipeline_id)
    build_graph(data.tasks, data.same_pipeline_edges)
    run = f"etl-craft run --pipeline_code {pipeline_code}"
    tasks: dict[str, Any] = {
        INIT_TASK: {
            "bash_command": f"{run} --init-only",
            "depends_on": [],
            "trigger_rule": "all_success",
        }
    }
    upstream_ids = {edge.depends_on_task_id for edge in data.same_pipeline_edges}
    for task in sorted(data.tasks, key=lambda t: codes[t.task_id]):
        edges = [e for e in data.same_pipeline_edges if e.task_id == task.task_id]
        tasks[codes[task.task_id]] = {
            "bash_command": f"{run} --task_code {codes[task.task_id]}",
            "depends_on": sorted(codes[e.depends_on_task_id] for e in edges) or [INIT_TASK],
            "trigger_rule": trigger_rule(
                task.run_condition or "ALL", [e.dependency_type for e in edges]
            ),
        }
    leaves = sorted(codes[t.task_id] for t in data.tasks if t.task_id not in upstream_ids)
    tasks[FINALIZE_TASK] = {
        "bash_command": f"{run} --finalize-only",
        "depends_on": leaves or [INIT_TASK],
        "trigger_rule": "all_done",
    }

    dag = _dag_settings(config, detail, tasks)
    pipeline_dependencies = fetch_pipeline_dependency_edges(conn, pipeline_id)
    if pipeline_dependencies:
        dag["pipeline_dependencies"] = [
            {
                "depends_on_pipeline": e.depends_on_pipeline_code,
                "dependency_type": e.dependency_type,
            }
            for e in pipeline_dependencies
        ]
    cross = [
        (codes[task_id], edge)
        for task_id in sorted(data.cross_pipeline_task_ids)
        for edge in fetch_cross_pipeline_task_edges(conn, task_id)
    ]
    if cross:
        dag["cross_pipeline_task_dependencies"] = [
            {
                "task": task_code,
                "depends_on_pipeline": edge.depends_on_label.split(".", 1)[0],
                "depends_on_task": edge.depends_on_label.split(".", 1)[1],
                "dependency_type": edge.dependency_type,
            }
            for task_code, edge in sorted(
                cross, key=lambda pair: (pair[0], pair[1].depends_on_label)
            )
        ]
    return dag


def _dag_settings(
    config: ConnectorConfig, detail: PipelineDetail, tasks: dict[str, Any]
) -> dict[str, Any]:
    """Return a pipeline's DAG settings around ``tasks``."""
    defaults = config.dag_defaults
    email_on_failure = bool(_first(detail.email_on_failure, defaults.email_on_failure, False))
    default_args: dict[str, Any] = {
        "owner": detail.created_by,
        "retries": _first(detail.retries, defaults.retries, DEFAULT_RETRIES),
        "retry_delay_minutes": _first(
            detail.retry_delay_minutes, defaults.retry_delay_minutes, DEFAULT_RETRY_DELAY_MINUTES
        ),
        "depends_on_past": _first(detail.depends_on_past, defaults.depends_on_past, False),
        "email_on_failure": email_on_failure,
    }
    if email_on_failure:
        default_args["email"] = _first(detail.email_recipients, defaults.email_recipients, [])
    return {
        "dag_id": detail.pipeline_code,
        "description": detail.description,
        "schedule": detail.run_schedule if defaults.allow_schedule else None,
        "sla_hours": detail.sla_in_hours,
        "refresh_type": detail.refresh_type,
        "catchup": _first(detail.catchup, defaults.catchup, False),
        "max_active_runs": 1,
        "tags": _first(detail.tags, defaults.tags, [detail.refresh_type.lower()]),
        "default_args": default_args,
        "tasks": tasks,
    }


def _remote_pipeline_dag(
    conn: Connection, config: ConnectorConfig, pipeline_code: str
) -> dict[str, Any]:
    """Return the DAG of ``pipeline_code`` holding every rule, for remote mode.

    ``__init__`` comes first, so every task the orchestrator runs has a run to bind to, even one
    that runs because a sensor failed (a ``FAILURE`` or ``ALWAYS`` dependency). Then the sensors
    on other pipelines, then those on other pipelines' tasks, each before its task. A task with
    no other upstream step waits for the sensors on other pipelines, or for ``__init__``.
    """
    require_supported(conn, config, pipeline_code)
    pipeline_id = resolve_pipeline_id(conn, pipeline_code)
    detail = fetch_pipeline_detail(conn, pipeline_id)
    data = fetch_pipeline_graph(conn, pipeline_id)
    codes = fetch_task_codes(conn, pipeline_id)
    build_graph(data.tasks, data.same_pipeline_edges)
    run = f"etl-craft run --pipeline_code {pipeline_code}"
    tasks: dict[str, Any] = {
        INIT_TASK: {
            "bash_command": f"{run} --init-only --run-date {RUN_DATE_TEMPLATE}",
            "depends_on": [],
            "trigger_rule": "all_success",
        }
    }
    base: list[str] = []
    if not config.dag_defaults.global_dag:
        for edge in sorted(
            fetch_pipeline_dependency_edges(conn, pipeline_id),
            key=lambda e: e.depends_on_pipeline_code,
        ):
            name = f"__wait_for_{edge.depends_on_pipeline_code}__"
            tasks[name] = _sensor(
                edge.depends_on_pipeline_code,
                None,
                DAG_SENSOR_STATES[edge.dependency_type],
                [INIT_TASK],
            )
            base.append(name)
    base = base or [INIT_TASK]
    upstream_ids = {edge.depends_on_task_id for edge in data.same_pipeline_edges}
    steps: dict[str, Any] = {}
    for task in sorted(data.tasks, key=lambda t: codes[t.task_id]):
        edges = [e for e in data.same_pipeline_edges if e.task_id == task.task_id]
        depends_on = [codes[e.depends_on_task_id] for e in edges]
        kinds = [e.dependency_type for e in edges]
        if task.task_id in data.cross_pipeline_task_ids:
            for cross in fetch_cross_pipeline_task_edges(conn, task.task_id):
                upstream_pipeline, upstream_task = cross.depends_on_label.split(".", 1)
                name = f"__wait_for_{cross.depends_on_label}__"
                tasks[name] = _sensor(
                    upstream_pipeline,
                    upstream_task,
                    TASK_SENSOR_STATES[cross.dependency_type],
                    base,
                )
                depends_on.append(name)
                kinds.append(SENSOR_TYPE)
        steps[codes[task.task_id]] = {
            "bash_command": f"{run} --task_code {codes[task.task_id]}",
            "depends_on": sorted(depends_on) or base,
            "trigger_rule": trigger_rule(task.run_condition or "ALL", kinds),
        }
    tasks.update(steps)
    leaves = sorted(codes[t.task_id] for t in data.tasks if t.task_id not in upstream_ids)
    tasks[FINALIZE_TASK] = {
        "bash_command": f"{run} --finalize-only",
        "depends_on": leaves or [INIT_TASK],
        "trigger_rule": "all_done",
    }
    return _dag_settings(config, detail, tasks)


def _sensor(
    dag_id: str, task_id: str | None, states: tuple[list[str], list[str]], depends_on: list[str]
) -> dict[str, Any]:
    allowed, failed = states
    return {
        "sensor": {
            "external_dag_id": dag_id,
            "external_task_id": task_id,
            "allowed_states": allowed,
            "failed_states": failed,
        },
        "depends_on": depends_on,
        "trigger_rule": "all_success",
    }


def global_dag(conn: Connection, config: ConnectorConfig) -> dict[str, Any]:
    """Return the DAG that triggers each pipeline's DAG in pipeline-dependency order.

    It holds every pipeline that depends on another or is depended on. ``ConfigurationError``
    unless Orchestration's ``Global_dag`` is on; in remote mode, ``RemoteUnsupportedError`` for a
    pipeline with rules the orchestrator does not support.
    """
    if not config.dag_defaults.global_dag:
        raise ConfigurationError(
            "the global DAG is off: set Global_dag: true in craft-connector.yml's Orchestration "
            "section to generate it"
        )
    rows = conn.execute(statement(conn, "all_pipeline_dependency_edges")).all()
    edges: dict[str, list[tuple[str, str]]] = {}
    for row in rows:
        edges.setdefault(row.pipeline_code, []).append(
            (row.depends_on_pipeline_code, row.dependency_type)
        )
        edges.setdefault(row.depends_on_pipeline_code, [])
    if config.mode == Mode.REMOTE:
        for code in sorted(edges):
            require_supported(conn, config, code)
    return {
        "dag_id": GLOBAL_DAG_ID,
        "pipelines": {
            code: {
                "trigger_dag_id": code,
                "depends_on": [upstream for upstream, _ in edges[code]],
                "trigger_rule": trigger_rule("ALL", [kind for _, kind in edges[code]]),
            }
            for code in sorted(edges)
        },
    }


def docs_dag(config: ConnectorConfig) -> dict[str, Any]:
    """Return the DAG that writes the catalog site again on ``Docs_site.Schedule``.

    ``ConfigurationError`` when no schedule is set.
    """
    schedule = config.docs_site.schedule
    if schedule is None:
        raise ConfigurationError(
            "Docs_site.Schedule is not set: name when the catalog site is written again, as a "
            "cron expression such as '0 2 * * *', in craft-connector.yml's Docs_site section"
        )
    defaults = config.dag_defaults
    email_on_failure = bool(defaults.email_on_failure)
    default_args: dict[str, Any] = {
        "owner": "etl-craft",
        "retries": _first(defaults.retries, DEFAULT_RETRIES),
        "retry_delay_minutes": _first(defaults.retry_delay_minutes, DEFAULT_RETRY_DELAY_MINUTES),
        "depends_on_past": False,
        "email_on_failure": email_on_failure,
    }
    if email_on_failure:
        default_args["email"] = defaults.email_recipients or []
    return {
        "dag_id": DOCS_DAG_ID,
        "description": "Writes the etl-craft catalog site again, with the latest runs.",
        "schedule": schedule if defaults.allow_schedule else None,
        "catchup": False,
        "tags": ["etl-craft", "docs"],
        "default_args": default_args,
        "tasks": {
            DOCS_TASK: {
                "bash_command": "etl-craft generate-docs",
                "depends_on": [],
                "trigger_rule": "all_success",
            }
        },
    }


def to_yaml(dag: dict[str, Any], mode: Mode = Mode.LOCAL) -> str:
    """Return a DAG as YAML, under the header that says how to read it in ``mode``."""
    header = REMOTE_HEADER if mode == Mode.REMOTE else HEADER
    return header + yaml.safe_dump(dag, sort_keys=False, default_flow_style=False)
