-- Rebuild the metadata tables with code checks, retaining ids and their sequence high watermarks.
CREATE TEMP TABLE etl_craft_code_sequences AS SELECT name, seq FROM sqlite_sequence WHERE name IN ('CFG_PIPELINES', 'CFG_TASKS');
CREATE TABLE CFG_PIPELINES_new (
    PIPELINE_ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    PIPELINE_CODE        VARCHAR NOT NULL,
    PIPELINE_NAME        VARCHAR NOT NULL,
    DESCRIPTION          VARCHAR,
    RUN_SCHEDULE         VARCHAR,
    SLA_IN_HOURS         NUMERIC,
    REFRESH_TYPE         VARCHAR NOT NULL,
    ACTIVE_FLAG          VARCHAR NOT NULL DEFAULT 'Y',
    PIPELINE_PARAMETERS  TEXT,
    CREATED_BY           VARCHAR DEFAULT 'etl-craft',
    CREATE_DATE          TIMESTAMP DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'now') || '000+00:00'),
    UPDATED_BY           VARCHAR DEFAULT 'etl-craft',
    UPDATED_DATE         TIMESTAMP DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'now') || '000+00:00'),
    CONSTRAINT ck_pipelines_code CHECK (PIPELINE_CODE GLOB '[A-Za-z]*' AND PIPELINE_CODE NOT GLOB '*[^A-Za-z0-9_]*' AND length(PIPELINE_CODE) <= 128 AND instr(PIPELINE_CODE, char(0)) = 0),
    CONSTRAINT ck_pipelines_refresh_type CHECK (REFRESH_TYPE IN ('FULL', 'INCREMENTAL')),
    CONSTRAINT ck_pipelines_active_flag  CHECK (ACTIVE_FLAG IN ('Y', 'N')),
    CONSTRAINT ck_pipelines_parameters_json
        CHECK (PIPELINE_PARAMETERS IS NULL OR json_valid(PIPELINE_PARAMETERS))
);
INSERT INTO CFG_PIPELINES_new (PIPELINE_ID, PIPELINE_CODE, PIPELINE_NAME, DESCRIPTION, RUN_SCHEDULE, SLA_IN_HOURS, REFRESH_TYPE, ACTIVE_FLAG, PIPELINE_PARAMETERS, CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATED_DATE) SELECT PIPELINE_ID, PIPELINE_CODE, PIPELINE_NAME, DESCRIPTION, RUN_SCHEDULE, SLA_IN_HOURS, REFRESH_TYPE, ACTIVE_FLAG, PIPELINE_PARAMETERS, CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATED_DATE FROM CFG_PIPELINES;
DROP TABLE CFG_PIPELINES;
ALTER TABLE CFG_PIPELINES_new RENAME TO CFG_PIPELINES;
UPDATE sqlite_sequence SET seq = max(seq, coalesce((SELECT seq FROM etl_craft_code_sequences WHERE name = 'CFG_PIPELINES'), seq)) WHERE name = 'CFG_PIPELINES';
CREATE UNIQUE INDEX ux_pipelines_code_active
    ON CFG_PIPELINES (PIPELINE_CODE) WHERE ACTIVE_FLAG = 'Y';
CREATE TRIGGER trg_audit_cfg_pipelines AFTER UPDATE ON CFG_PIPELINES
BEGIN
    UPDATE CFG_PIPELINES
    SET CREATED_BY = OLD.CREATED_BY,
        CREATE_DATE = OLD.CREATE_DATE,
        UPDATED_DATE = strftime('%Y-%m-%d %H:%M:%f', 'now') || '000+00:00'
    WHERE PIPELINE_ID = NEW.PIPELINE_ID;
END;
CREATE TABLE CFG_TASKS_new (
    TASK_ID              INTEGER PRIMARY KEY AUTOINCREMENT,
    TASK_CODE            VARCHAR NOT NULL,
    TASK_TYPE            VARCHAR NOT NULL,
    PIPELINE_ID          BIGINT NOT NULL REFERENCES CFG_PIPELINES(PIPELINE_ID),
    HANDLER              VARCHAR NOT NULL,
    RUN_CONDITION        VARCHAR,
    RUN_CONDITION_COUNT  INT,
    ACTIVE_FLAG          VARCHAR NOT NULL DEFAULT 'Y',
    CREATED_BY           VARCHAR DEFAULT 'etl-craft',
    CREATE_DATE          TIMESTAMP DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'now') || '000+00:00'),
    UPDATED_BY           VARCHAR DEFAULT 'etl-craft',
    UPDATED_DATE         TIMESTAMP DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'now') || '000+00:00'),
    CONSTRAINT ck_tasks_code CHECK (TASK_CODE GLOB '[A-Za-z]*' AND TASK_CODE NOT GLOB '*[^A-Za-z0-9_]*' AND length(TASK_CODE) <= 128 AND instr(TASK_CODE, char(0)) = 0),
    CONSTRAINT ck_tasks_task_type     CHECK (TASK_TYPE IN ('INGESTION','ETL')),
    CONSTRAINT ck_tasks_handler       CHECK (HANDLER IN ('PYTHON','SQL','BUSINESS_RULES','EMAIL_ALERT')),
    CONSTRAINT ck_tasks_active_flag   CHECK (ACTIVE_FLAG IN ('Y','N')),
    CONSTRAINT ck_tasks_run_condition CHECK (RUN_CONDITION IS NULL OR RUN_CONDITION IN ('ALL','ANY','N')),
    CONSTRAINT ck_tasks_run_condition_count CHECK (
        (COALESCE(RUN_CONDITION, '') = 'N' AND RUN_CONDITION_COUNT IS NOT NULL
            AND RUN_CONDITION_COUNT >= 1)
        OR (RUN_CONDITION IS NOT 'N' AND RUN_CONDITION_COUNT IS NULL)
    )
);
INSERT INTO CFG_TASKS_new (TASK_ID, TASK_CODE, TASK_TYPE, PIPELINE_ID, HANDLER, RUN_CONDITION, RUN_CONDITION_COUNT, ACTIVE_FLAG, CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATED_DATE) SELECT TASK_ID, TASK_CODE, TASK_TYPE, PIPELINE_ID, HANDLER, RUN_CONDITION, RUN_CONDITION_COUNT, ACTIVE_FLAG, CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATED_DATE FROM CFG_TASKS;
DROP TABLE CFG_TASKS;
ALTER TABLE CFG_TASKS_new RENAME TO CFG_TASKS;
UPDATE sqlite_sequence SET seq = max(seq, coalesce((SELECT seq FROM etl_craft_code_sequences WHERE name = 'CFG_TASKS'), seq)) WHERE name = 'CFG_TASKS';
CREATE UNIQUE INDEX ux_tasks_code_active
    ON CFG_TASKS (PIPELINE_ID, TASK_CODE) WHERE ACTIVE_FLAG = 'Y';
CREATE TRIGGER trg_audit_cfg_tasks AFTER UPDATE ON CFG_TASKS
BEGIN
    UPDATE CFG_TASKS
    SET CREATED_BY = OLD.CREATED_BY,
        CREATE_DATE = OLD.CREATE_DATE,
        UPDATED_DATE = strftime('%Y-%m-%d %H:%M:%f', 'now') || '000+00:00'
    WHERE TASK_ID = NEW.TASK_ID;
END;
INSERT INTO sqlite_sequence (name, seq)
SELECT name, seq FROM etl_craft_code_sequences s
WHERE NOT EXISTS (SELECT 1 FROM sqlite_sequence c WHERE c.name = s.name);
DROP TABLE etl_craft_code_sequences;
