-- Give runs stable identities while preserving references and sequence high watermarks.
CREATE TEMP TABLE etl_craft_run_sequence AS SELECT name, seq FROM sqlite_sequence WHERE name = 'AUD_PIPELINES_RUN_LOG';
CREATE TABLE AUD_PIPELINES_RUN_LOG_new (
    PIPELINE_RUN_ID  INTEGER PRIMARY KEY AUTOINCREMENT,
    PIPELINE_ID      BIGINT NOT NULL REFERENCES CFG_PIPELINES(PIPELINE_ID),
    START_DATE       TIMESTAMP NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'now') || '000+00:00'),
    END_DATE         TIMESTAMP,
    STATUS           VARCHAR NOT NULL,
    SLA_STATUS       VARCHAR(8),
    RUN_DATE         DATE,
    BACKFILL         VARCHAR(1) NOT NULL DEFAULT 'N',
    RUN_KEY          VARCHAR NOT NULL DEFAULT ('manual:' || lower(hex(randomblob(16)))),
    TRIGGER_KIND     VARCHAR NOT NULL DEFAULT 'MANUAL',
    OWNER_ID         VARCHAR,
    LEASE_EXPIRES_AT TIMESTAMP,
    OUTPUT_REVISION  INT NOT NULL DEFAULT 1,
    CONFIG_SHA256    VARCHAR(64),
    CONSTRAINT ck_pipeline_run_trigger_kind CHECK (TRIGGER_KIND IN ('SCHEDULE','MANUAL','BACKFILL','ORCHESTRATOR','STAND_IN')),
    CONSTRAINT ck_pipeline_run_backfill CHECK (BACKFILL IN ('Y','N')),
    CONSTRAINT ck_pipeline_run_status CHECK (STATUS IN ('IN-PROGRESS','SUCCESS','FAILED','SKIPPED','CANCELLED')),
    CONSTRAINT ck_pipeline_run_sla_status CHECK (SLA_STATUS IN ('MET','BREACHED'))
);
INSERT INTO AUD_PIPELINES_RUN_LOG_new (PIPELINE_RUN_ID, PIPELINE_ID, START_DATE, END_DATE, STATUS, SLA_STATUS, RUN_DATE, BACKFILL, RUN_KEY, TRIGGER_KIND) SELECT PIPELINE_RUN_ID, PIPELINE_ID, START_DATE, END_DATE, STATUS, SLA_STATUS, RUN_DATE, BACKFILL, 'legacy:' || PIPELINE_RUN_ID, CASE WHEN BACKFILL = 'Y' THEN 'BACKFILL' ELSE 'MANUAL' END FROM AUD_PIPELINES_RUN_LOG;
DROP TABLE AUD_PIPELINES_RUN_LOG;
ALTER TABLE AUD_PIPELINES_RUN_LOG_new RENAME TO AUD_PIPELINES_RUN_LOG;
UPDATE sqlite_sequence SET seq = max(seq, coalesce((SELECT seq FROM etl_craft_run_sequence), seq)) WHERE name = 'AUD_PIPELINES_RUN_LOG';
INSERT INTO sqlite_sequence (name, seq) SELECT name, seq FROM etl_craft_run_sequence s WHERE NOT EXISTS (SELECT 1 FROM sqlite_sequence c WHERE c.name = s.name);
DROP TABLE etl_craft_run_sequence;
CREATE UNIQUE INDEX ux_pipeline_run_one_active
    ON AUD_PIPELINES_RUN_LOG (PIPELINE_ID) WHERE STATUS = 'IN-PROGRESS';
CREATE INDEX ix_pipeline_run_pipeline ON AUD_PIPELINES_RUN_LOG (PIPELINE_ID);
CREATE UNIQUE INDEX ux_pipeline_run_key ON AUD_PIPELINES_RUN_LOG (PIPELINE_ID, RUN_KEY);
ALTER TABLE CFG_PIPELINE_DEPENDENCY ADD COLUMN CONSUME_REPAIRS         VARCHAR(1) NOT NULL DEFAULT 'Y' CONSTRAINT ck_pipedep_consume_repairs CHECK (CONSUME_REPAIRS IN ('Y','N'));
ALTER TABLE CFG_TASK_DEPENDENCY ADD COLUMN CONSUME_REPAIRS         VARCHAR(1) NOT NULL DEFAULT 'Y' CONSTRAINT ck_taskdep_consume_repairs CHECK (CONSUME_REPAIRS IN ('Y','N'));
ALTER TABLE AUD_DEPENDENCY_CONSUMPTION ADD COLUMN CONSUMED_REVISION INT NOT NULL DEFAULT 1;

-- Attempt history and the dependencies judged at admission.
CREATE TABLE AUD_TASK_ATTEMPTS (
    ATTEMPT_ID       INTEGER PRIMARY KEY AUTOINCREMENT,
    TASK_RUN_ID      BIGINT NOT NULL REFERENCES AUD_TASK_RUN_LOG(TASK_RUN_ID),
    ATTEMPT_NUMBER   INT NOT NULL,
    STATUS           VARCHAR NOT NULL,
    OWNER_ID         VARCHAR,
    LEASE_EXPIRES_AT TIMESTAMP,
    HEARTBEAT_AT     TIMESTAMP,
    QUEUED_AT        TIMESTAMP,
    CLAIMED_AT       TIMESTAMP,
    STARTED_AT       TIMESTAMP,
    ENDED_AT         TIMESTAMP,
    HOST             VARCHAR,
    PID              INT,
    PROCESS_START    VARCHAR,
    EXIT_CODE        INT,
    SOURCE_COUNT     BIGINT,
    TARGET_COUNT     BIGINT,
    INSERT_COUNT     BIGINT,
    UPDATE_COUNT     BIGINT,
    DELETE_COUNT     BIGINT,
    ROWS_WRITTEN     BIGINT,
    ERROR_MESSAGE    VARCHAR,
    TASK_LOG         VARCHAR,
    LOG_PATH         VARCHAR,
    REQUESTED_BY     VARCHAR,
    CONSTRAINT ck_attempt_status CHECK (STATUS IN ('QUEUED','CLAIMED','RUNNING','SUCCESS','FAILED','TIMED_OUT','CANCELLED','LOST'))
);
CREATE UNIQUE INDEX ux_attempt_number ON AUD_TASK_ATTEMPTS (TASK_RUN_ID, ATTEMPT_NUMBER);
CREATE UNIQUE INDEX ux_attempt_one_active ON AUD_TASK_ATTEMPTS (TASK_RUN_ID)
    WHERE STATUS IN ('QUEUED','CLAIMED','RUNNING');
CREATE INDEX ix_attempt_status_lease ON AUD_TASK_ATTEMPTS (STATUS, LEASE_EXPIRES_AT);

-- Each dependency judged at admission, with the selected upstream revision and reason.
CREATE TABLE AUD_GATE_DECISIONS (
    DECISION_ID              INTEGER PRIMARY KEY AUTOINCREMENT,
    PIPELINE_RUN_ID          BIGINT NOT NULL REFERENCES AUD_PIPELINES_RUN_LOG(PIPELINE_RUN_ID),
    ATTEMPT_ID               BIGINT REFERENCES AUD_TASK_ATTEMPTS(ATTEMPT_ID),
    PIPELINE_DEPENDENCY_ID   BIGINT REFERENCES CFG_PIPELINE_DEPENDENCY(PIPELINE_DEPENDENCY_ID),
    TASK_DEPENDENCY_ID       BIGINT REFERENCES CFG_TASK_DEPENDENCY(TASK_DEPENDENCY_ID),
    SELECTED_PIPELINE_RUN_ID BIGINT REFERENCES AUD_PIPELINES_RUN_LOG(PIPELINE_RUN_ID),
    SELECTED_TASK_RUN_ID     BIGINT REFERENCES AUD_TASK_RUN_LOG(TASK_RUN_ID),
    SELECTED_REVISION        INT,
    RESULT                   VARCHAR NOT NULL,
    REASON                   VARCHAR NOT NULL,
    DECIDED_AT               TIMESTAMP NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'now') || '000+00:00'),
    CONSTRAINT ck_gate_one_dependency CHECK (
        (PIPELINE_DEPENDENCY_ID IS NOT NULL AND TASK_DEPENDENCY_ID IS NULL)
        OR (PIPELINE_DEPENDENCY_ID IS NULL AND TASK_DEPENDENCY_ID IS NOT NULL)
    ),
    CONSTRAINT ck_gate_result CHECK (RESULT IN ('SATISFIED','UNSATISFIED','BYPASSED'))
);

-- Skipped tasks have no execution attempt; their summary retains the gate outcome.
INSERT INTO AUD_TASK_ATTEMPTS (
    TASK_RUN_ID, ATTEMPT_NUMBER, STATUS, STARTED_AT, ENDED_AT,
    SOURCE_COUNT, TARGET_COUNT, INSERT_COUNT, UPDATE_COUNT, DELETE_COUNT,
    ROWS_WRITTEN, ERROR_MESSAGE, TASK_LOG
)
SELECT TASK_RUN_ID, ATTEMPT_COUNT,
       CASE WHEN STATUS = 'IN-PROGRESS' THEN 'RUNNING' ELSE STATUS END,
       START_DATE, END_DATE, SOURCE_COUNT, TARGET_COUNT, INSERT_COUNT, UPDATE_COUNT,
       DELETE_COUNT, ROWS_WRITTEN, ERROR_MESSAGE, TASK_LOG
FROM AUD_TASK_RUN_LOG WHERE STATUS <> 'SKIPPED';
