-- Persist schedule policies and allow pending scheduled runs.
ALTER TABLE CFG_PIPELINES ADD COLUMN SCHEDULE_TIMEZONE VARCHAR;
ALTER TABLE CFG_PIPELINES ADD COLUMN CATCHUP VARCHAR(1) NOT NULL DEFAULT 'N' CONSTRAINT ck_schedule_catchup CHECK (CATCHUP IN ('Y','N'));
ALTER TABLE CFG_PIPELINES ADD COLUMN MAX_CATCHUP_RUNS INT NOT NULL DEFAULT 1 CONSTRAINT ck_schedule_catchup_runs CHECK (MAX_CATCHUP_RUNS > 0 AND typeof(MAX_CATCHUP_RUNS) = 'integer');
ALTER TABLE CFG_PIPELINES ADD COLUMN OVERLAP_POLICY VARCHAR NOT NULL DEFAULT 'SKIP' CONSTRAINT ck_schedule_overlap CHECK (OVERLAP_POLICY IN ('SKIP','QUEUE'));
ALTER TABLE CFG_PIPELINES ADD COLUMN SCHEDULE_START_DATE DATE;
CREATE TEMP TABLE etl_craft_schedule_sequence AS SELECT name, seq FROM sqlite_sequence WHERE name='AUD_PIPELINES_RUN_LOG';
CREATE TABLE AUD_PIPELINES_RUN_LOG_new (
    PIPELINE_RUN_ID  INTEGER PRIMARY KEY AUTOINCREMENT,
    PIPELINE_ID      BIGINT NOT NULL REFERENCES CFG_PIPELINES(PIPELINE_ID),
    START_DATE       TIMESTAMP NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'now') || '000+00:00'),
    END_DATE         TIMESTAMP,
    STATUS           VARCHAR NOT NULL,
    SLA_STATUS       VARCHAR(8),
    RUN_DATE         DATE,
    BACKFILL         VARCHAR(1) NOT NULL DEFAULT 'N',
    RUN_KEY          VARCHAR NOT NULL DEFAULT ('manual:' || lower(hex(randomblob(16)))),
    TRIGGER_KIND     VARCHAR NOT NULL DEFAULT 'MANUAL',
    OWNER_ID         VARCHAR,
    LEASE_EXPIRES_AT TIMESTAMP,
    OUTPUT_REVISION  INT NOT NULL DEFAULT 1,
    CONFIG_SHA256    VARCHAR(64),
    STARTED_BY VARCHAR DEFAULT (etl_craft_actor()),
    STARTED_BY_KIND VARCHAR DEFAULT (etl_craft_actor_kind()) CONSTRAINT ck_aud_pipelines_run_log_started_by_kind CHECK (STARTED_BY_KIND IN ('HUMAN','SCHEDULE','ORCHESTRATOR','WORKER','SYSTEM')),
    ENDED_BY VARCHAR,
    ENDED_BY_KIND VARCHAR CONSTRAINT ck_aud_pipelines_run_log_ended_by_kind CHECK (ENDED_BY_KIND IN ('HUMAN','SCHEDULE','ORCHESTRATOR','WORKER','SYSTEM')),
    REPAIR_PENDING   VARCHAR NOT NULL DEFAULT 'N' CONSTRAINT ck_run_repair_pending CHECK (REPAIR_PENDING IN ('Y','N')),
    CONSTRAINT ck_pipeline_run_trigger_kind CHECK (TRIGGER_KIND IN ('SCHEDULE','MANUAL','BACKFILL','ORCHESTRATOR','STAND_IN')),
    CONSTRAINT ck_pipeline_run_backfill CHECK (BACKFILL IN ('Y','N')),
    CONSTRAINT ck_pipeline_run_status CHECK (STATUS IN ('QUEUED','IN-PROGRESS','SUCCESS','FAILED','SKIPPED','CANCELLED')),
    CONSTRAINT ck_pipeline_run_sla_status CHECK (SLA_STATUS IN ('MET','BREACHED'))
);
INSERT INTO AUD_PIPELINES_RUN_LOG_new (PIPELINE_RUN_ID,PIPELINE_ID,START_DATE,END_DATE,STATUS,SLA_STATUS,RUN_DATE,BACKFILL,RUN_KEY,TRIGGER_KIND,OWNER_ID,LEASE_EXPIRES_AT,OUTPUT_REVISION,CONFIG_SHA256,STARTED_BY,STARTED_BY_KIND,ENDED_BY,ENDED_BY_KIND,REPAIR_PENDING) SELECT PIPELINE_RUN_ID,PIPELINE_ID,START_DATE,END_DATE,STATUS,SLA_STATUS,RUN_DATE,BACKFILL,RUN_KEY,TRIGGER_KIND,OWNER_ID,LEASE_EXPIRES_AT,OUTPUT_REVISION,CONFIG_SHA256,STARTED_BY,STARTED_BY_KIND,ENDED_BY,ENDED_BY_KIND,REPAIR_PENDING FROM AUD_PIPELINES_RUN_LOG;
DROP TABLE AUD_PIPELINES_RUN_LOG;
ALTER TABLE AUD_PIPELINES_RUN_LOG_new RENAME TO AUD_PIPELINES_RUN_LOG;
UPDATE sqlite_sequence SET seq=max(seq, coalesce((SELECT seq FROM etl_craft_schedule_sequence), seq)) WHERE name='AUD_PIPELINES_RUN_LOG';
INSERT INTO sqlite_sequence (name, seq) SELECT name, seq FROM etl_craft_schedule_sequence s WHERE NOT EXISTS (SELECT 1 FROM sqlite_sequence c WHERE c.name=s.name);
DROP TABLE etl_craft_schedule_sequence;
-- At most one IN-PROGRESS run per pipeline: this index is what makes run-id resolution safe
-- when several task processes start at once.
CREATE UNIQUE INDEX ux_pipeline_run_one_active
    ON AUD_PIPELINES_RUN_LOG (PIPELINE_ID) WHERE STATUS = 'IN-PROGRESS';
CREATE INDEX ix_pipeline_run_pipeline ON AUD_PIPELINES_RUN_LOG (PIPELINE_ID);
CREATE UNIQUE INDEX ux_pipeline_run_key ON AUD_PIPELINES_RUN_LOG (PIPELINE_ID, RUN_KEY);
CREATE TRIGGER trg_actor_guard_aud_pipelines_run_log_insert BEFORE INSERT ON AUD_PIPELINES_RUN_LOG
BEGIN
    SELECT CASE WHEN etl_craft_actor() IS NULL THEN RAISE(ABORT, 'AUD_PIPELINES_RUN_LOG is written only by etl-craft; use etl-craft mark, cancel or run, or a project migration (etl-craft migrate)') END;
END;
CREATE TRIGGER trg_actor_guard_aud_pipelines_run_log_update BEFORE UPDATE ON AUD_PIPELINES_RUN_LOG
BEGIN
    SELECT CASE WHEN etl_craft_actor() IS NULL THEN RAISE(ABORT, 'AUD_PIPELINES_RUN_LOG is written only by etl-craft; use etl-craft mark, cancel or run, or a project migration (etl-craft migrate)') END;
END;
CREATE TRIGGER trg_actor_guard_aud_pipelines_run_log_delete BEFORE DELETE ON AUD_PIPELINES_RUN_LOG
BEGIN
    SELECT CASE WHEN etl_craft_actor() IS NULL THEN RAISE(ABORT, 'AUD_PIPELINES_RUN_LOG is written only by etl-craft; use etl-craft mark, cancel or run, or a project migration (etl-craft migrate)') END;
END;
-- The run log is mutable; stamp its inserting actor before the transaction commits.
CREATE TRIGGER trg_attribute_run_insert AFTER INSERT ON AUD_PIPELINES_RUN_LOG
BEGIN
    UPDATE AUD_PIPELINES_RUN_LOG SET STARTED_BY=COALESCE(NEW.STARTED_BY, etl_craft_actor()), STARTED_BY_KIND=COALESCE(NEW.STARTED_BY_KIND, etl_craft_actor_kind()), ENDED_BY=CASE WHEN NEW.END_DATE IS NOT NULL THEN COALESCE(NEW.ENDED_BY, etl_craft_actor()) ELSE NEW.ENDED_BY END, ENDED_BY_KIND=CASE WHEN NEW.END_DATE IS NOT NULL THEN COALESCE(NEW.ENDED_BY_KIND, etl_craft_actor_kind()) ELSE NEW.ENDED_BY_KIND END WHERE PIPELINE_RUN_ID=NEW.PIPELINE_RUN_ID;
END;
CREATE INDEX ix_pipeline_schedule_key ON AUD_PIPELINES_RUN_LOG (PIPELINE_ID, RUN_KEY) WHERE TRIGGER_KIND = 'SCHEDULE';
