-- etl-craft Engine DB schema for PostgreSQL.
--
-- `etl-craft init-db` applies this file to an empty database in one transaction; `migrate`
-- carries an existing database forward with the files in migrations/. The SQLite schema beside
-- it defines the same tables and columns, so every Engine DB query reads the same shape.
--
-- CFG_ tables hold what to run, written by the team and reviewed like code. AUD_ tables are
-- written by the engine as it runs. Every CFG_ row carries ACTIVE_FLAG; rows are retired by
-- setting it to 'N', never deleted, and each code is unique among active rows only.

-- Stamps the audit columns on every CFG_ insert and update. CREATED_BY and CREATE_DATE never
-- change after the insert. The values mean something only when every person and service
-- touching the Engine DB connects as its own role.
CREATE OR REPLACE FUNCTION trg_set_audit_columns()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.CREATED_BY   := current_user;
        NEW.CREATE_DATE  := now();
        NEW.UPDATED_BY   := current_user;
        NEW.UPDATED_DATE := now();
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.CREATED_BY   := OLD.CREATED_BY;
        NEW.CREATE_DATE  := OLD.CREATE_DATE;
        NEW.UPDATED_BY   := current_user;
        NEW.UPDATED_DATE := now();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- A task dependency without DEPENDS_ON_PIPELINE_ID is on a task in the same pipeline.
CREATE OR REPLACE FUNCTION trg_default_depends_on_pipeline()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.DEPENDS_ON_PIPELINE_ID IS NULL THEN
        NEW.DEPENDS_ON_PIPELINE_ID := NEW.PIPELINE_ID;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE CFG_PIPELINES (
    PIPELINE_ID          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PIPELINE_CODE        VARCHAR NOT NULL,
    PIPELINE_NAME        VARCHAR NOT NULL,
    DESCRIPTION          VARCHAR,
    RUN_SCHEDULE         VARCHAR,
    SLA_IN_HOURS         NUMERIC,
    REFRESH_TYPE         VARCHAR NOT NULL,
    ACTIVE_FLAG          VARCHAR NOT NULL DEFAULT 'Y',
    PIPELINE_PARAMETERS  JSONB,
    CREATED_BY           VARCHAR,
    CREATE_DATE          TIMESTAMPTZ,
    UPDATED_BY           VARCHAR,
    UPDATED_DATE         TIMESTAMPTZ,
    CONSTRAINT ck_pipelines_refresh_type CHECK (REFRESH_TYPE IN ('FULL', 'INCREMENTAL')),
    CONSTRAINT ck_pipelines_active_flag  CHECK (ACTIVE_FLAG IN ('Y', 'N'))
);
CREATE UNIQUE INDEX ux_pipelines_code_active
    ON CFG_PIPELINES (PIPELINE_CODE) WHERE ACTIVE_FLAG = 'Y';
CREATE TRIGGER trg_audit_cfg_pipelines
    BEFORE INSERT OR UPDATE ON CFG_PIPELINES
    FOR EACH ROW EXECUTE FUNCTION trg_set_audit_columns();
COMMENT ON TABLE CFG_PIPELINES IS 'One row per pipeline. PIPELINE_CODE is the key the command line uses; REFRESH_TYPE decides what $$pipeline_id becomes.';

CREATE TABLE CFG_PIPELINE_DEPENDENCY (
    PIPELINE_DEPENDENCY_ID  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PIPELINE_ID             BIGINT NOT NULL REFERENCES CFG_PIPELINES(PIPELINE_ID),
    DEPENDS_ON_PIPELINE_ID  BIGINT NOT NULL REFERENCES CFG_PIPELINES(PIPELINE_ID),
    DEPENDENCY_TYPE         VARCHAR NOT NULL,
    ACTIVE_FLAG             VARCHAR NOT NULL DEFAULT 'Y',
    CREATED_BY              VARCHAR,
    CREATE_DATE             TIMESTAMPTZ,
    UPDATED_BY              VARCHAR,
    UPDATED_DATE            TIMESTAMPTZ,
    CONSTRAINT ck_pipedep_type        CHECK (DEPENDENCY_TYPE IN ('SUCCESS','FAILURE','ALWAYS','HAS_DATA')),
    CONSTRAINT ck_pipedep_active_flag CHECK (ACTIVE_FLAG IN ('Y','N')),
    CONSTRAINT ck_pipedep_no_self_dep CHECK (PIPELINE_ID <> DEPENDS_ON_PIPELINE_ID)
);
CREATE UNIQUE INDEX ux_pipedep_edge_active
    ON CFG_PIPELINE_DEPENDENCY (PIPELINE_ID, DEPENDS_ON_PIPELINE_ID, DEPENDENCY_TYPE)
    WHERE ACTIVE_FLAG = 'Y';
CREATE INDEX ix_pipedep_depends_on ON CFG_PIPELINE_DEPENDENCY (DEPENDS_ON_PIPELINE_ID);
CREATE TRIGGER trg_audit_cfg_pipeline_dependency
    BEFORE INSERT OR UPDATE ON CFG_PIPELINE_DEPENDENCY
    FOR EACH ROW EXECUTE FUNCTION trg_set_audit_columns();
COMMENT ON TABLE CFG_PIPELINE_DEPENDENCY IS 'A pipeline waits for another pipeline''s outcome. Checked against AUD_PIPELINE_DEPENDENCY_TRACKER when the pipeline starts.';

CREATE TABLE CFG_TASKS (
    TASK_ID              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TASK_CODE            VARCHAR NOT NULL,
    TASK_TYPE            VARCHAR NOT NULL,
    PIPELINE_ID          BIGINT NOT NULL REFERENCES CFG_PIPELINES(PIPELINE_ID),
    HANDLER              VARCHAR NOT NULL,
    RUN_CONDITION        VARCHAR,
    RUN_CONDITION_COUNT  INT,
    ACTIVE_FLAG          VARCHAR NOT NULL DEFAULT 'Y',
    CREATED_BY           VARCHAR,
    CREATE_DATE          TIMESTAMPTZ,
    UPDATED_BY           VARCHAR,
    UPDATED_DATE         TIMESTAMPTZ,
    CONSTRAINT ck_tasks_task_type       CHECK (TASK_TYPE IN ('INGESTION','ETL')),
    CONSTRAINT ck_tasks_handler         CHECK (HANDLER IN ('PYTHON','SQL','BUSINESS_RULES','EMAIL_ALERT')),
    CONSTRAINT ck_tasks_active_flag     CHECK (ACTIVE_FLAG IN ('Y','N')),
    CONSTRAINT ck_tasks_run_condition   CHECK (RUN_CONDITION IS NULL OR RUN_CONDITION IN ('ALL','ANY','N')),
    CONSTRAINT ck_tasks_run_condition_count CHECK (
        (COALESCE(RUN_CONDITION, '') = 'N' AND RUN_CONDITION_COUNT IS NOT NULL
            AND RUN_CONDITION_COUNT >= 1)
        OR (RUN_CONDITION IS DISTINCT FROM 'N' AND RUN_CONDITION_COUNT IS NULL)
    )
);
CREATE UNIQUE INDEX ux_tasks_code_active
    ON CFG_TASKS (PIPELINE_ID, TASK_CODE) WHERE ACTIVE_FLAG = 'Y';
CREATE TRIGGER trg_audit_cfg_tasks
    BEFORE INSERT OR UPDATE ON CFG_TASKS
    FOR EACH ROW EXECUTE FUNCTION trg_set_audit_columns();
COMMENT ON TABLE CFG_TASKS IS 'One row per task. HANDLER runs it; its settings are CFG_TASK_PARAMETERS rows.';
COMMENT ON COLUMN CFG_TASKS.RUN_CONDITION IS 'ALL | ANY | N: how many of this task''s dependencies must be satisfied. NULL means ALL.';
COMMENT ON COLUMN CFG_TASKS.RUN_CONDITION_COUNT IS 'How many dependencies must be satisfied when RUN_CONDITION = ''N''; NULL for every other condition.';

CREATE TABLE CFG_TASK_DEPENDENCY (
    TASK_DEPENDENCY_ID      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PIPELINE_ID             BIGINT NOT NULL REFERENCES CFG_PIPELINES(PIPELINE_ID),
    TASK_ID                 BIGINT NOT NULL REFERENCES CFG_TASKS(TASK_ID),
    DEPENDS_ON_PIPELINE_ID  BIGINT REFERENCES CFG_PIPELINES(PIPELINE_ID),
    DEPENDS_ON_TASK_ID      BIGINT NOT NULL REFERENCES CFG_TASKS(TASK_ID),
    DEPENDENCY_TYPE         VARCHAR NOT NULL,
    ACTIVE_FLAG             VARCHAR NOT NULL DEFAULT 'Y',
    CREATED_BY              VARCHAR,
    CREATE_DATE             TIMESTAMPTZ,
    UPDATED_BY              VARCHAR,
    UPDATED_DATE            TIMESTAMPTZ,
    CONSTRAINT ck_taskdep_type        CHECK (DEPENDENCY_TYPE IN ('SUCCESS','FAILURE','ALWAYS','HAS_DATA')),
    CONSTRAINT ck_taskdep_active_flag CHECK (ACTIVE_FLAG IN ('Y','N')),
    CONSTRAINT ck_taskdep_no_self_dep CHECK (NOT (TASK_ID = DEPENDS_ON_TASK_ID AND PIPELINE_ID = DEPENDS_ON_PIPELINE_ID))
);
CREATE TRIGGER trg_default_taskdep_pipeline
    BEFORE INSERT OR UPDATE ON CFG_TASK_DEPENDENCY
    FOR EACH ROW EXECUTE FUNCTION trg_default_depends_on_pipeline();
CREATE TRIGGER trg_audit_cfg_task_dependency
    BEFORE INSERT OR UPDATE ON CFG_TASK_DEPENDENCY
    FOR EACH ROW EXECUTE FUNCTION trg_set_audit_columns();
CREATE UNIQUE INDEX ux_taskdep_edge_active
    ON CFG_TASK_DEPENDENCY (TASK_ID, DEPENDS_ON_PIPELINE_ID, DEPENDS_ON_TASK_ID, DEPENDENCY_TYPE)
    WHERE ACTIVE_FLAG = 'Y';
CREATE INDEX ix_taskdep_depends_on ON CFG_TASK_DEPENDENCY (DEPENDS_ON_TASK_ID);
COMMENT ON TABLE CFG_TASK_DEPENDENCY IS 'A task waits for another task''s outcome. Same-pipeline dependencies order the pipeline''s waves; one on another pipeline''s task is checked against AUD_TASK_DEPENDENCY_TRACKER when the task starts.';

CREATE TABLE CFG_TASK_PARAMETERS (
    TASK_PARAMETER_ID  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TASK_ID            BIGINT NOT NULL REFERENCES CFG_TASKS(TASK_ID),
    PARAMETER_NAME     VARCHAR NOT NULL,
    PARAMETER_VALUE    VARCHAR,
    ACTIVE_FLAG        VARCHAR NOT NULL DEFAULT 'Y',
    CREATED_BY         VARCHAR,
    CREATE_DATE        TIMESTAMPTZ,
    UPDATED_BY         VARCHAR,
    UPDATED_DATE       TIMESTAMPTZ,
    CONSTRAINT ck_taskparameters_active_flag CHECK (ACTIVE_FLAG IN ('Y','N'))
);
CREATE UNIQUE INDEX ux_taskparameters_name_active
    ON CFG_TASK_PARAMETERS (TASK_ID, PARAMETER_NAME) WHERE ACTIVE_FLAG = 'Y';
CREATE TRIGGER trg_audit_cfg_task_parameters
    BEFORE INSERT OR UPDATE ON CFG_TASK_PARAMETERS
    FOR EACH ROW EXECUTE FUNCTION trg_set_audit_columns();
COMMENT ON TABLE CFG_TASK_PARAMETERS IS 'A task''s settings as name and value pairs (SQL_ACTION, TARGET_OBJECT, SOURCE_SQL, ...). Which names each handler reads is documented in the task parameter reference.';

CREATE TABLE CFG_BUSINESS_RULES (
    BUSINESS_RULE_ID          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BUSINESS_RULE_NAME        VARCHAR NOT NULL,
    PIPELINE_ID               BIGINT NOT NULL REFERENCES CFG_PIPELINES(PIPELINE_ID),
    TASK_ID                   BIGINT NOT NULL REFERENCES CFG_TASKS(TASK_ID),
    BUSINESS_RULE_SQL         VARCHAR NOT NULL,
    BUSINESS_RULE_TYPE        VARCHAR NOT NULL,
    BUSINESS_RULE_KEY_COLUMN  VARCHAR NOT NULL,
    TARGET_TABLE              VARCHAR NOT NULL,
    SEQUENCE_NUMBER           BIGINT NOT NULL,
    ACTIVE_FLAG               VARCHAR NOT NULL DEFAULT 'Y',
    CREATED_BY                VARCHAR,
    CREATE_DATE               TIMESTAMPTZ,
    UPDATED_BY                VARCHAR,
    UPDATED_DATE              TIMESTAMPTZ,
    CONSTRAINT ck_br_type        CHECK (BUSINESS_RULE_TYPE IN ('INCOMPLETE','REJECT','REPORT')),
    CONSTRAINT ck_br_active_flag CHECK (ACTIVE_FLAG IN ('Y','N'))
);
CREATE UNIQUE INDEX ux_br_name_active
    ON CFG_BUSINESS_RULES (TASK_ID, BUSINESS_RULE_NAME) WHERE ACTIVE_FLAG = 'Y';
CREATE INDEX ix_br_pipeline ON CFG_BUSINESS_RULES (PIPELINE_ID);
CREATE TRIGGER trg_audit_cfg_business_rules
    BEFORE INSERT OR UPDATE ON CFG_BUSINESS_RULES
    FOR EACH ROW EXECUTE FUNCTION trg_set_audit_columns();
COMMENT ON TABLE CFG_BUSINESS_RULES IS 'Checks a BUSINESS_RULES task runs against a warehouse table. TARGET_TABLE must have a single-column primary key, named by BUSINESS_RULE_KEY_COLUMN; `validate` checks it in the warehouse.';

CREATE TABLE AUD_PIPELINES_RUN_LOG (
    PIPELINE_RUN_ID  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PIPELINE_ID      BIGINT NOT NULL REFERENCES CFG_PIPELINES(PIPELINE_ID),
    START_DATE       TIMESTAMPTZ NOT NULL DEFAULT now(),
    END_DATE         TIMESTAMPTZ,
    STATUS           VARCHAR NOT NULL,
    SLA_STATUS       VARCHAR(8),
    CONSTRAINT ck_pipeline_run_status CHECK (STATUS IN ('IN-PROGRESS','SUCCESS','FAILED','SKIPPED','CANCELLED')),
    CONSTRAINT ck_pipeline_run_sla_status CHECK (SLA_STATUS IN ('MET','BREACHED'))
);
-- At most one IN-PROGRESS run per pipeline: this index is what makes run-id resolution safe
-- when several task processes start at once.
CREATE UNIQUE INDEX ux_pipeline_run_one_active
    ON AUD_PIPELINES_RUN_LOG (PIPELINE_ID) WHERE STATUS = 'IN-PROGRESS';
CREATE INDEX ix_pipeline_run_pipeline ON AUD_PIPELINES_RUN_LOG (PIPELINE_ID);
COMMENT ON TABLE AUD_PIPELINES_RUN_LOG IS 'One row per pipeline run. Tasks never receive pipeline_run_id; each resolves the pipeline''s one IN-PROGRESS run here.';

CREATE TABLE AUD_TASK_RUN_LOG (
    TASK_RUN_ID      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TASK_ID          BIGINT NOT NULL REFERENCES CFG_TASKS(TASK_ID),
    PIPELINE_RUN_ID  BIGINT NOT NULL REFERENCES AUD_PIPELINES_RUN_LOG(PIPELINE_RUN_ID),
    START_DATE       TIMESTAMPTZ NOT NULL DEFAULT now(),
    END_DATE         TIMESTAMPTZ,
    STATUS           VARCHAR NOT NULL,
    SOURCE_COUNT     BIGINT,
    TARGET_COUNT     BIGINT,
    INSERT_COUNT     BIGINT,
    UPDATE_COUNT     BIGINT,
    DELETE_COUNT     BIGINT,
    ERROR_MESSAGE    VARCHAR,
    TASK_LOG         VARCHAR,
    ATTEMPT_COUNT    INT NOT NULL DEFAULT 1,
    CONSTRAINT ck_task_run_status CHECK (STATUS IN ('IN-PROGRESS','SUCCESS','FAILED','SKIPPED','CANCELLED'))
);
CREATE UNIQUE INDEX ux_task_run_one_per_pipeline_run
    ON AUD_TASK_RUN_LOG (TASK_ID, PIPELINE_RUN_ID);
CREATE INDEX ix_task_run_pipeline_run ON AUD_TASK_RUN_LOG (PIPELINE_RUN_ID);

-- Every change an operator made to a run: a task or a run marked, a stand-in run recorded, a run
-- cancelled or reopened, a task reset to run again or run again, a task run without its
-- dependencies, and a dependency gate bypassed. TASK_ID is NULL for a change to the run.
-- FROM_STATUS and PREVIOUS_MESSAGE keep what the row held before, so nothing is erased;
-- TO_STATUS is NULL for a task reset to not run yet.
CREATE TABLE AUD_RUN_INTERVENTIONS (
    INTERVENTION_ID   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PIPELINE_ID       BIGINT NOT NULL REFERENCES CFG_PIPELINES(PIPELINE_ID),
    PIPELINE_RUN_ID   BIGINT NOT NULL REFERENCES AUD_PIPELINES_RUN_LOG(PIPELINE_RUN_ID),
    TASK_ID           BIGINT REFERENCES CFG_TASKS(TASK_ID),
    ACTION            VARCHAR(24) NOT NULL,
    FROM_STATUS       VARCHAR(16),
    TO_STATUS         VARCHAR(16),
    TARGET_COUNT      BIGINT,
    PREVIOUS_MESSAGE  VARCHAR,
    REASON            VARCHAR NOT NULL,
    REQUESTED_BY      VARCHAR NOT NULL,
    REQUESTED_AT      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_intervention_action CHECK (ACTION IN ('MARK','NEW_RUN','CANCEL','REOPEN','RESET',
                                                     'GATE_BYPASS','IGNORE_DEPENDENCIES','RERUN'))
);

CREATE INDEX ix_run_interventions_run ON AUD_RUN_INTERVENTIONS (PIPELINE_RUN_ID);
COMMENT ON TABLE AUD_TASK_RUN_LOG IS 'One row per task per pipeline run. A retry updates the row and counts the attempt in ATTEMPT_COUNT; a task already SUCCESS or SKIPPED is not run again.';

CREATE TABLE AUD_BUSINESS_RULES_RUN_LOG (
    BUSINESS_RULE_RUN_ID  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BUSINESS_RULE_ID      BIGINT NOT NULL REFERENCES CFG_BUSINESS_RULES(BUSINESS_RULE_ID),
    TASK_RUN_ID           BIGINT NOT NULL REFERENCES AUD_TASK_RUN_LOG(TASK_RUN_ID),
    START_DATE            TIMESTAMPTZ NOT NULL DEFAULT now(),
    END_DATE              TIMESTAMPTZ,
    STATUS                VARCHAR NOT NULL,
    CONSTRAINT ck_br_run_status CHECK (STATUS IN ('IN-PROGRESS','SUCCESS','FAILED','SKIPPED'))
);
CREATE UNIQUE INDEX ux_br_run_one_per_task_run
    ON AUD_BUSINESS_RULES_RUN_LOG (BUSINESS_RULE_ID, TASK_RUN_ID);
COMMENT ON TABLE AUD_BUSINESS_RULES_RUN_LOG IS 'Whether each business rule ran, per task run. What a rule found is in AUD_BUSINESS_RULES_RESULTS.';

CREATE TABLE AUD_BUSINESS_RULES_RESULTS (
    BUSINESS_RULE_RESULT_ID  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BUSINESS_RULE_RUN_ID     BIGINT NOT NULL REFERENCES AUD_BUSINESS_RULES_RUN_LOG(BUSINESS_RULE_RUN_ID),
    BUSINESS_RULE_ID         BIGINT NOT NULL REFERENCES CFG_BUSINESS_RULES(BUSINESS_RULE_ID),
    BUSINESS_RULE_KEY        VARCHAR NOT NULL,
    TARGET_TABLE             VARCHAR NOT NULL,
    STATUS                   VARCHAR NOT NULL,
    ACTIVE_FLAG              VARCHAR NOT NULL DEFAULT 'Y',
    START_DATE               TIMESTAMPTZ NOT NULL DEFAULT now(),
    END_DATE                 TIMESTAMPTZ,
    CONSTRAINT ck_brresults_status      CHECK (STATUS IN ('INCOMPLETE','REJECT','REPORT')),
    CONSTRAINT ck_brresults_active_flag CHECK (ACTIVE_FLAG IN ('Y','N'))
);
CREATE INDEX ix_brresults_run ON AUD_BUSINESS_RULES_RESULTS (BUSINESS_RULE_RUN_ID);
CREATE INDEX ix_brresults_rule ON AUD_BUSINESS_RULES_RESULTS (BUSINESS_RULE_ID);
COMMENT ON TABLE AUD_BUSINESS_RULES_RESULTS IS 'One row per record a business rule flagged. A record that passes on a later run is cleared: ACTIVE_FLAG = ''N'' and END_DATE set.';

CREATE TABLE AUD_TASK_OFFSET_TRACKER (
    TASK_ID                 BIGINT PRIMARY KEY REFERENCES CFG_TASKS(TASK_ID),
    OFFSET_TYPE             VARCHAR NOT NULL,
    OFFSET_VALUE            VARCHAR,
    LAST_UPDATED_TIMESTAMP  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_offset_type CHECK (OFFSET_TYPE IN ('NUMBER','TEXT','TIMESTAMP'))
);
COMMENT ON TABLE AUD_TASK_OFFSET_TRACKER IS 'The watermark an incremental ingestion script reads and advances.';

CREATE TABLE AUD_COLUMN_LINEAGE (
    COLUMN_LINEAGE_ID  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TASK_ID            BIGINT NOT NULL REFERENCES CFG_TASKS(TASK_ID),
    SOURCE_SQL_HASH    VARCHAR NOT NULL,
    TARGET_OBJECT      VARCHAR NOT NULL,
    TARGET_COLUMN      VARCHAR NOT NULL,
    SOURCE_OBJECT      VARCHAR,
    SOURCE_COLUMN      VARCHAR,
    TRANSFORMATION     VARCHAR,
    COMPUTED_AT        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_column_lineage_task ON AUD_COLUMN_LINEAGE (TASK_ID, SOURCE_SQL_HASH);
CREATE INDEX ix_column_lineage_target ON AUD_COLUMN_LINEAGE (TARGET_OBJECT, TARGET_COLUMN);
CREATE INDEX ix_column_lineage_source ON AUD_COLUMN_LINEAGE (SOURCE_OBJECT, SOURCE_COLUMN);
COMMENT ON TABLE AUD_COLUMN_LINEAGE IS 'Column lineage parsed from each SQL task''s SOURCE_SQL, keyed by a hash of what it was parsed from. A row whose hash no longer matches is replaced, never read.';

-- The URL the catalog site is published at, one row per URL: the latest is current. A publish
-- that is given another URL fails unless told to accept it, so shared links keep working.
CREATE TABLE AUD_DOCS_PUBLICATION (
    DOCS_PUBLICATION_ID  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PUBLISHED_URL        VARCHAR NOT NULL,
    FIRST_PUBLISHED      TIMESTAMPTZ NOT NULL DEFAULT now(),
    LAST_PUBLISHED       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE AUD_TASK_DOCUMENTATION (
    TASK_DOCUMENTATION_ID  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TASK_ID                BIGINT NOT NULL REFERENCES CFG_TASKS(TASK_ID),
    VERSION                INT NOT NULL,
    DOCUMENTATION_HASH     VARCHAR NOT NULL,
    DOCUMENTATION          VARCHAR NOT NULL,
    RECORDED_AT            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_task_documentation_version UNIQUE (TASK_ID, VERSION)
);
CREATE INDEX ix_task_documentation_task ON AUD_TASK_DOCUMENTATION (TASK_ID, VERSION DESC);
COMMENT ON TABLE AUD_TASK_DOCUMENTATION IS 'Each version of a task''s DOCUMENTATION parameter. A new version is recorded only when the text changes.';

CREATE TABLE AUD_PIPELINE_DEPENDENCY_TRACKER (
    PIPELINE_DEPENDENCY_ID         BIGINT PRIMARY KEY REFERENCES CFG_PIPELINE_DEPENDENCY(PIPELINE_DEPENDENCY_ID),
    PIPELINE_ID                    BIGINT NOT NULL REFERENCES CFG_PIPELINES(PIPELINE_ID),
    DEPENDS_ON_PIPELINE_ID         BIGINT NOT NULL REFERENCES CFG_PIPELINES(PIPELINE_ID),
    LAST_CONSUMED_PIPELINE_RUN_ID  BIGINT REFERENCES AUD_PIPELINES_RUN_LOG(PIPELINE_RUN_ID),
    LAST_CONSUMED_END_DATE         TIMESTAMPTZ,
    LAST_UPDATED_TIMESTAMP         TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE AUD_PIPELINE_DEPENDENCY_TRACKER IS 'The upstream run each pipeline dependency last consumed. An upstream run satisfies the dependency only if it is newer than that one and has the outcome the dependency waits for, so pipelines on different schedules never reuse a stale run.';

CREATE TABLE AUD_TASK_DEPENDENCY_TRACKER (
    TASK_DEPENDENCY_ID         BIGINT PRIMARY KEY REFERENCES CFG_TASK_DEPENDENCY(TASK_DEPENDENCY_ID),
    TASK_ID                    BIGINT NOT NULL REFERENCES CFG_TASKS(TASK_ID),
    PIPELINE_ID                BIGINT NOT NULL REFERENCES CFG_PIPELINES(PIPELINE_ID),
    DEPENDS_ON_TASK_ID         BIGINT NOT NULL REFERENCES CFG_TASKS(TASK_ID),
    DEPENDS_ON_PIPELINE_ID     BIGINT NOT NULL REFERENCES CFG_PIPELINES(PIPELINE_ID),
    LAST_CONSUMED_TASK_RUN_ID  BIGINT REFERENCES AUD_TASK_RUN_LOG(TASK_RUN_ID),
    LAST_CONSUMED_END_DATE     TIMESTAMPTZ,
    LAST_UPDATED_TIMESTAMP     TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE AUD_TASK_DEPENDENCY_TRACKER IS 'The same as AUD_PIPELINE_DEPENDENCY_TRACKER, for a task''s dependency on a task in another pipeline. Same-pipeline dependencies are checked against the current run instead.';

CREATE TABLE SCHEMA_MIGRATIONS (
    SOURCE      VARCHAR NOT NULL,
    VERSION     VARCHAR NOT NULL,
    CHECKSUM    VARCHAR(64) NOT NULL,
    APPLIED_AT  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_schema_migrations PRIMARY KEY (SOURCE, VERSION),
    CONSTRAINT ck_schema_migrations_source CHECK (SOURCE IN ('ENGINE', 'PROJECT')),
    CONSTRAINT ck_schema_migrations_checksum CHECK (CHECKSUM ~ '^[0-9a-f]{64}$')
);
COMMENT ON TABLE SCHEMA_MIGRATIONS IS 'Every migration file applied: the packaged ENGINE stream and the team''s own PROJECT stream, each with the SHA-256 of the file as applied.';
