"""Commands in their order in ``etl-craft --help``."""

from etl_craft.cli.commands import (
    audit,
    cancel,
    clone,
    docs_version,
    doctor,
    generate_docs,
    generate_yml,
    graph,
    history,
    init_db,
    lineage,
    list_pipelines,
    mark,
    migrate,
    pause,
    publish_docs,
    reconcile,
    rehash,
    run,
    server,
    setup,
    steps,
    upgrade_targets,
    validate,
)
from etl_craft.cli.commands.common import Command as Command

COMMANDS: tuple[Command, ...] = (
    run.COMMAND,
    server.COMMAND,
    mark.COMMAND,
    cancel.COMMAND,
    reconcile.COMMAND,
    rehash.COMMAND,
    upgrade_targets.COMMAND,
    pause.command("pause"),
    pause.command("resume"),
    list_pipelines.COMMAND,
    graph.COMMAND,
    steps.COMMAND,
    history.COMMAND,
    audit.COMMAND,
    lineage.COMMAND,
    docs_version.COMMAND,
    generate_docs.COMMAND,
    publish_docs.COMMAND,
    generate_yml.COMMAND,
    clone.COMMAND,
    validate.COMMAND,
    doctor.COMMAND,
    setup.COMMAND,
    init_db.COMMAND,
    migrate.COMMAND,
)
