-- 0002_column_lineage_and_docs.sql
--
-- Adds AUD_COLUMN_LINEAGE (cached column-level lineage, parsed from SOURCE_SQL
-- with sqlglot) and AUD_TASK_DOCUMENTATION (version history for the
-- DOCUMENTATION task parameter). Mirrors the same change made directly in
-- schema.sql -- see its own POST-SIGNOFF CHANGES block.
--
-- Additive only. Nothing existing is altered, so this is safe to apply to a
-- database mid-flight.

CREATE TABLE IF NOT EXISTS AUD_COLUMN_LINEAGE (
    COLUMN_LINEAGE_ID  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TASK_ID            BIGINT NOT NULL REFERENCES CFG_TASKS(TASK_ID),
    SOURCE_SQL_HASH    VARCHAR NOT NULL,
    TARGET_OBJECT      VARCHAR NOT NULL,
    TARGET_COLUMN      VARCHAR NOT NULL,
    SOURCE_OBJECT      VARCHAR,
    SOURCE_COLUMN      VARCHAR,
    TRANSFORMATION     VARCHAR,
    COMPUTED_AT        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_column_lineage_task ON AUD_COLUMN_LINEAGE (TASK_ID, SOURCE_SQL_HASH);

CREATE INDEX IF NOT EXISTS ix_column_lineage_target ON AUD_COLUMN_LINEAGE (TARGET_OBJECT, TARGET_COLUMN);

CREATE INDEX IF NOT EXISTS ix_column_lineage_source ON AUD_COLUMN_LINEAGE (SOURCE_OBJECT, SOURCE_COLUMN);

CREATE TABLE IF NOT EXISTS AUD_TASK_DOCUMENTATION (
    TASK_DOCUMENTATION_ID  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TASK_ID                BIGINT NOT NULL REFERENCES CFG_TASKS(TASK_ID),
    VERSION                INT NOT NULL,
    DOCUMENTATION_HASH     VARCHAR NOT NULL,
    DOCUMENTATION          VARCHAR NOT NULL,
    RECORDED_AT            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_task_documentation_version UNIQUE (TASK_ID, VERSION)
);

CREATE INDEX IF NOT EXISTS ix_task_documentation_task ON AUD_TASK_DOCUMENTATION (TASK_ID, VERSION DESC);
