-- 0004_migration_streams_and_checksums.sql
--
-- Separates packaged ENGINE migrations from a deployment's PROJECT migrations
-- and stores the SHA-256 checksum of every newly recorded file.  It mirrors
-- SCHEMA_MIGRATIONS in schema.sql.  Existing filename-only ledger rows become
-- LEGACY until migrate.py can safely assign them to one of the two streams.

ALTER TABLE SCHEMA_MIGRATIONS ADD COLUMN IF NOT EXISTS SOURCE VARCHAR;

ALTER TABLE SCHEMA_MIGRATIONS ADD COLUMN IF NOT EXISTS CHECKSUM VARCHAR(64);

UPDATE SCHEMA_MIGRATIONS SET SOURCE = 'LEGACY' WHERE SOURCE IS NULL;

ALTER TABLE SCHEMA_MIGRATIONS ALTER COLUMN SOURCE SET DEFAULT 'LEGACY';

ALTER TABLE SCHEMA_MIGRATIONS ALTER COLUMN SOURCE SET NOT NULL;

ALTER TABLE SCHEMA_MIGRATIONS DROP CONSTRAINT IF EXISTS schema_migrations_pkey;

ALTER TABLE SCHEMA_MIGRATIONS DROP CONSTRAINT IF EXISTS pk_schema_migrations;

ALTER TABLE SCHEMA_MIGRATIONS ADD CONSTRAINT pk_schema_migrations PRIMARY KEY (SOURCE, VERSION);

ALTER TABLE SCHEMA_MIGRATIONS DROP CONSTRAINT IF EXISTS ck_schema_migrations_source;

ALTER TABLE SCHEMA_MIGRATIONS ADD CONSTRAINT ck_schema_migrations_source
    CHECK (SOURCE IN ('ENGINE', 'PROJECT', 'LEGACY'));

ALTER TABLE SCHEMA_MIGRATIONS DROP CONSTRAINT IF EXISTS ck_schema_migrations_checksum;

ALTER TABLE SCHEMA_MIGRATIONS ADD CONSTRAINT ck_schema_migrations_checksum
    CHECK (CHECKSUM IS NULL OR CHECKSUM ~ '^[0-9a-f]{64}$');
