SELECT ATTEMPT_ID AS attempt_id, ATTEMPT_NUMBER AS attempt_number, OWNER_ID AS owner_id,
STATUS AS status FROM AUD_TASK_ATTEMPTS
WHERE TASK_RUN_ID = :task_run_id AND STATUS IN ('QUEUED','CLAIMED','RUNNING')
