-- Every active pipeline's PIPELINE_PARAMETERS, as stored.
SELECT PIPELINE_CODE AS pipeline_code, PIPELINE_PARAMETERS AS pipeline_parameters
FROM CFG_PIPELINES
WHERE ACTIVE_FLAG = 'Y'
ORDER BY PIPELINE_CODE
