SELECT p.PIPELINE_CODE AS pipeline_code, t.TASK_CODE AS task_code
FROM AUD_TASK_ATTEMPTS a
JOIN AUD_TASK_RUN_LOG r ON r.TASK_RUN_ID = a.TASK_RUN_ID
JOIN AUD_PIPELINES_RUN_LOG pr ON pr.PIPELINE_RUN_ID = r.PIPELINE_RUN_ID
JOIN CFG_PIPELINES p ON p.PIPELINE_ID = pr.PIPELINE_ID
JOIN CFG_TASKS t ON t.TASK_ID = r.TASK_ID
WHERE a.ATTEMPT_ID = :attempt_id
