-- Record that :pipeline_id consumed upstream run :run_id through :dependency_id.
INSERT INTO AUD_PIPELINE_DEPENDENCY_TRACKER (
    PIPELINE_DEPENDENCY_ID, PIPELINE_ID, DEPENDS_ON_PIPELINE_ID,
    LAST_CONSUMED_PIPELINE_RUN_ID, LAST_CONSUMED_END_DATE, LAST_UPDATED_TIMESTAMP
)
SELECT :dependency_id, :pipeline_id, :depends_on_pipeline_id, :run_id, END_DATE, :now
FROM AUD_PIPELINES_RUN_LOG
WHERE PIPELINE_RUN_ID = :run_id
ON CONFLICT (PIPELINE_DEPENDENCY_ID) DO UPDATE SET
    LAST_CONSUMED_PIPELINE_RUN_ID = EXCLUDED.LAST_CONSUMED_PIPELINE_RUN_ID,
    LAST_CONSUMED_END_DATE = EXCLUDED.LAST_CONSUMED_END_DATE,
    LAST_UPDATED_TIMESTAMP = EXCLUDED.LAST_UPDATED_TIMESTAMP
