-- Record that :task_id consumed upstream task run :run_id through :dependency_id.
INSERT INTO AUD_TASK_DEPENDENCY_TRACKER (
    TASK_DEPENDENCY_ID, TASK_ID, PIPELINE_ID, DEPENDS_ON_TASK_ID, DEPENDS_ON_PIPELINE_ID,
    LAST_CONSUMED_TASK_RUN_ID, LAST_CONSUMED_END_DATE, LAST_UPDATED_TIMESTAMP
)
SELECT :dependency_id, :task_id, :pipeline_id, :depends_on_task_id, :depends_on_pipeline_id,
       :run_id, END_DATE, :now
FROM AUD_TASK_RUN_LOG
WHERE TASK_RUN_ID = :run_id
ON CONFLICT (TASK_DEPENDENCY_ID) DO UPDATE SET
    LAST_CONSUMED_TASK_RUN_ID = EXCLUDED.LAST_CONSUMED_TASK_RUN_ID,
    LAST_CONSUMED_END_DATE = EXCLUDED.LAST_CONSUMED_END_DATE,
    LAST_UPDATED_TIMESTAMP = EXCLUDED.LAST_UPDATED_TIMESTAMP
