INSERT INTO AUD_DEPENDENCY_CONSUMPTION (TASK_DEPENDENCY_ID, PIPELINE_ID, PIPELINE_RUN_ID,
TASK_ID, DEPENDS_ON_PIPELINE_ID, CONSUMED_PIPELINE_RUN_ID, CONSUMED_TASK_RUN_ID,
CONSUMED_REVISION, CONSUMED_AT)
SELECT d.TASK_DEPENDENCY_ID AS task_dependency_id, r.PIPELINE_ID AS pipeline_id,
d.PIPELINE_RUN_ID AS pipeline_run_id, t.TASK_ID AS task_id,
u.PIPELINE_ID AS depends_on_pipeline_id, d.SELECTED_PIPELINE_RUN_ID AS consumed_pipeline_run_id,
d.SELECTED_TASK_RUN_ID AS consumed_task_run_id, d.SELECTED_REVISION AS consumed_revision,
:now AS consumed_at
FROM AUD_GATE_DECISIONS d JOIN AUD_TASK_ATTEMPTS a ON a.ATTEMPT_ID = d.ATTEMPT_ID
JOIN AUD_TASK_RUN_LOG t ON t.TASK_RUN_ID = a.TASK_RUN_ID
JOIN AUD_PIPELINES_RUN_LOG r ON r.PIPELINE_RUN_ID = d.PIPELINE_RUN_ID
JOIN AUD_PIPELINES_RUN_LOG u ON u.PIPELINE_RUN_ID = d.SELECTED_PIPELINE_RUN_ID
WHERE d.PIPELINE_RUN_ID = :run_id AND t.TASK_ID = :task_id
AND (CAST(:attempt_id AS bigint) IS NULL OR a.ATTEMPT_ID = CAST(:attempt_id AS bigint))
AND d.TASK_DEPENDENCY_ID IS NOT NULL AND d.RESULT = 'SATISFIED' AND a.STATUS = 'SUCCESS'
AND NOT EXISTS (SELECT 1 FROM AUD_DEPENDENCY_CONSUMPTION c
WHERE c.PIPELINE_RUN_ID = d.PIPELINE_RUN_ID AND c.TASK_ID = t.TASK_ID
AND c.TASK_DEPENDENCY_ID = d.TASK_DEPENDENCY_ID AND c.CONSUMED_TASK_RUN_ID = d.SELECTED_TASK_RUN_ID
AND c.CONSUMED_REVISION = d.SELECTED_REVISION)
