INSERT INTO AUD_DEPENDENCY_CONSUMPTION (PIPELINE_DEPENDENCY_ID, PIPELINE_ID, PIPELINE_RUN_ID,
DEPENDS_ON_PIPELINE_ID, CONSUMED_PIPELINE_RUN_ID, CONSUMED_REVISION, CONSUMED_AT)
SELECT d.PIPELINE_DEPENDENCY_ID AS pipeline_dependency_id, r.PIPELINE_ID AS pipeline_id,
d.PIPELINE_RUN_ID AS pipeline_run_id, u.PIPELINE_ID AS depends_on_pipeline_id,
d.SELECTED_PIPELINE_RUN_ID AS consumed_pipeline_run_id,
d.SELECTED_REVISION AS consumed_revision, :now AS consumed_at
FROM AUD_GATE_DECISIONS d
JOIN AUD_PIPELINES_RUN_LOG r ON r.PIPELINE_RUN_ID = d.PIPELINE_RUN_ID
JOIN AUD_PIPELINES_RUN_LOG u ON u.PIPELINE_RUN_ID = d.SELECTED_PIPELINE_RUN_ID
WHERE d.PIPELINE_RUN_ID = :run_id AND d.PIPELINE_DEPENDENCY_ID IS NOT NULL
AND d.RESULT = 'SATISFIED' AND r.STATUS = 'SUCCESS'
AND NOT EXISTS (SELECT 1 FROM AUD_DEPENDENCY_CONSUMPTION c
WHERE c.PIPELINE_RUN_ID = d.PIPELINE_RUN_ID AND c.PIPELINE_DEPENDENCY_ID = d.PIPELINE_DEPENDENCY_ID
AND c.CONSUMED_PIPELINE_RUN_ID = d.SELECTED_PIPELINE_RUN_ID AND c.CONSUMED_REVISION = d.SELECTED_REVISION)
