SELECT 'CFG_PIPELINES.PIPELINE_CODE' AS object, PIPELINE_ID AS object_id, PIPELINE_CODE AS code
FROM CFG_PIPELINES
UNION ALL
SELECT 'CFG_TASKS.TASK_CODE' AS object, TASK_ID AS object_id, TASK_CODE AS code
FROM CFG_TASKS
ORDER BY object, object_id;
