SELECT t.TASK_ID AS task_id, p.PARAMETER_NAME AS parameter_name, p.PARAMETER_VALUE AS parameter_value
FROM CFG_TASKS t JOIN CFG_TASK_PARAMETERS p ON p.TASK_ID = t.TASK_ID
JOIN CFG_PIPELINES r ON r.PIPELINE_ID = t.PIPELINE_ID
WHERE t.HANDLER = 'SQL' AND t.ACTIVE_FLAG = 'Y' AND r.ACTIVE_FLAG = 'Y' AND p.ACTIVE_FLAG = 'Y'
AND p.PARAMETER_NAME IN ('SQL_ACTION', 'TARGET_OBJECT', 'MERGE_COMPARE_COLUMNS', 'TABLE_FORMAT')
