SELECT r.TASK_ID AS task_id, a.TASK_RUN_ID AS task_run_id, a.ATTEMPT_ID AS attempt_id,
a.ATTEMPT_NUMBER AS attempt_number, a.STATUS AS status, a.RETRYABLE AS retryable,
a.NOT_BEFORE AS not_before
FROM AUD_TASK_ATTEMPTS a JOIN AUD_TASK_RUN_LOG r ON r.TASK_RUN_ID = a.TASK_RUN_ID
WHERE r.PIPELINE_RUN_ID = :pipeline_run_id AND NOT EXISTS (
SELECT 1 FROM AUD_TASK_ATTEMPTS newer WHERE newer.TASK_RUN_ID = a.TASK_RUN_ID
AND newer.ATTEMPT_NUMBER > a.ATTEMPT_NUMBER)
