SELECT PIPELINE_RUN_ID AS pipeline_run_id, STATUS AS status, OWNER_ID AS owner_id,
RUN_KEY AS run_key FROM AUD_PIPELINES_RUN_LOG
WHERE PIPELINE_ID = :pipeline_id AND (RUN_KEY = :run_key OR STATUS = 'IN-PROGRESS')
ORDER BY PIPELINE_RUN_ID DESC LIMIT 1
