INSERT INTO AUD_TARGET_HASH_VERSION (TARGET_OBJECT, HASH_VERSION, RECOMPUTED_AT)
VALUES (:target, :version, :now) ON CONFLICT (TARGET_OBJECT) DO UPDATE
SET HASH_VERSION = excluded.HASH_VERSION, RECOMPUTED_AT = excluded.RECOMPUTED_AT
