INSERT INTO AUD_GATE_WAITS (PIPELINE_RUN_ID, TASK_ID, FIRST_CHECK_AT, NEXT_CHECK_AT, LOOKS, WAIT_UNTIL)
VALUES (:pipeline_run_id, :task_id, :first_check_at, :next_check_at, :looks, :wait_until)
ON CONFLICT (PIPELINE_RUN_ID, (COALESCE(TASK_ID,0))) DO UPDATE SET
FIRST_CHECK_AT=excluded.FIRST_CHECK_AT, NEXT_CHECK_AT=excluded.NEXT_CHECK_AT,
LOOKS=excluded.LOOKS, WAIT_UNTIL=excluded.WAIT_UNTIL
