INSERT INTO AUD_TARGET_VIEW_STATEMENT (TARGET_OBJECT, STATEMENT_SHA256, RECORDED_AT)
VALUES (:target, :sha256, :now) ON CONFLICT (TARGET_OBJECT) DO UPDATE
SET STATEMENT_SHA256 = excluded.STATEMENT_SHA256, RECORDED_AT = excluded.RECORDED_AT
