-- Store :offset_value, of :offset_type, as the offset of :task_id.
INSERT INTO AUD_TASK_OFFSET_TRACKER (TASK_ID, OFFSET_TYPE, OFFSET_VALUE, LAST_UPDATED_TIMESTAMP)
VALUES (:task_id, :offset_type, :offset_value, :now)
ON CONFLICT (TASK_ID) DO UPDATE SET
    OFFSET_TYPE = EXCLUDED.OFFSET_TYPE,
    OFFSET_VALUE = EXCLUDED.OFFSET_VALUE,
    LAST_UPDATED_TIMESTAMP = EXCLUDED.LAST_UPDATED_TIMESTAMP
