UPDATE AUD_PIPELINES_RUN_LOG SET OWNER_ID = NULL, LEASE_EXPIRES_AT = NULL
WHERE PIPELINE_RUN_ID = :row_id AND OWNER_ID = :owner
 AND NOT EXISTS (SELECT 1 FROM AUD_TASK_ATTEMPTS a
 JOIN AUD_TASK_RUN_LOG t ON t.TASK_RUN_ID = a.TASK_RUN_ID
 WHERE t.PIPELINE_RUN_ID = AUD_PIPELINES_RUN_LOG.PIPELINE_RUN_ID
 AND a.STATUS IN ('QUEUED','CLAIMED','RUNNING'))
