UPDATE AUD_PIPELINES_RUN_LOG SET STATUS = :status, END_DATE = :now,
ENDED_BY = :actor, ENDED_BY_KIND = :actor_kind,
SLA_STATUS = COALESCE(SLA_STATUS, :sla_status)
WHERE PIPELINE_RUN_ID = :row_id AND STATUS = 'IN-PROGRESS' AND (OWNER_ID = :owner OR (OWNER_ID IS NULL AND :owner IS NULL))
AND NOT EXISTS (SELECT 1 FROM AUD_TASK_ATTEMPTS a
JOIN AUD_TASK_RUN_LOG t ON t.TASK_RUN_ID = a.TASK_RUN_ID
WHERE t.PIPELINE_RUN_ID = AUD_PIPELINES_RUN_LOG.PIPELINE_RUN_ID
AND a.STATUS IN ('CLAIMED','RUNNING'))
