UPDATE AUD_TASK_RUN_LOG SET TASK_LOG = :task_log
WHERE TASK_RUN_ID = :task_run_id
AND EXISTS (SELECT 1 FROM AUD_TASK_ATTEMPTS a
WHERE a.ATTEMPT_ID = :attempt_id AND a.TASK_RUN_ID = :task_run_id
AND a.STATUS != 'LOST'
AND (a.STATUS NOT IN ('QUEUED','CLAIMED','RUNNING') OR a.LEASE_EXPIRES_AT > :now)
AND a.OWNER_ID = :owner AND a.ATTEMPT_NUMBER = AUD_TASK_RUN_LOG.ATTEMPT_COUNT
AND AUD_TASK_RUN_LOG.STATUS = CASE
WHEN a.STATUS IN ('QUEUED','CLAIMED','RUNNING') THEN 'IN-PROGRESS'
WHEN a.STATUS IN ('LOST','TIMED_OUT') THEN 'FAILED' ELSE a.STATUS END)
AND NOT EXISTS (SELECT 1 FROM AUD_TASK_ATTEMPTS newer
WHERE newer.TASK_RUN_ID = :task_run_id AND newer.ATTEMPT_NUMBER > AUD_TASK_RUN_LOG.ATTEMPT_COUNT)
