UPDATE AUD_TASK_RUN_LOG SET STATUS = 'IN-PROGRESS', END_DATE = NULL,
START_DATE = :now, SOURCE_COUNT = NULL, TARGET_COUNT = NULL, INSERT_COUNT = NULL,
UPDATE_COUNT = NULL, DELETE_COUNT = NULL, ROWS_WRITTEN = NULL, ERROR_MESSAGE = NULL, TASK_LOG = NULL
WHERE TASK_RUN_ID = :row_id
AND NOT EXISTS (SELECT 1 FROM AUD_TASK_ATTEMPTS a WHERE a.TASK_RUN_ID = :row_id
AND a.STATUS IN ('QUEUED','CLAIMED','RUNNING'))
AND EXISTS (SELECT 1 FROM AUD_PIPELINES_RUN_LOG p
WHERE p.PIPELINE_RUN_ID = AUD_TASK_RUN_LOG.PIPELINE_RUN_ID AND p.STATUS = 'IN-PROGRESS')
