UPDATE AUD_PIPELINES_RUN_LOG SET STATUS='IN-PROGRESS', START_DATE=:now
WHERE PIPELINE_RUN_ID=:row_id AND STATUS='QUEUED' AND OWNER_ID IS NULL
AND NOT EXISTS (SELECT 1 FROM AUD_PIPELINES_RUN_LOG other
WHERE other.PIPELINE_ID=AUD_PIPELINES_RUN_LOG.PIPELINE_ID AND other.STATUS='IN-PROGRESS')
