UPDATE AUD_TASK_ATTEMPTS SET STATUS = 'CLAIMED', OWNER_ID = :owner, HOST = :host,
LEASE_EXPIRES_AT = :lease, HEARTBEAT_AT = :now, CLAIMED_AT = :now
WHERE ATTEMPT_ID = :row_id AND STATUS = 'QUEUED' AND OWNER_ID IS NULL
