UPDATE AUD_PIPELINES_RUN_LOG SET OWNER_ID = :owner, LEASE_EXPIRES_AT = :lease,
STARTED_BY = :actor, STARTED_BY_KIND = :actor_kind
WHERE PIPELINE_RUN_ID = :row_id AND STATUS = 'IN-PROGRESS' AND OWNER_ID IS NULL
