UPDATE AUD_PIPELINES_RUN_LOG SET STATUS = 'IN-PROGRESS',
END_DATE = NULL, ENDED_BY = NULL, ENDED_BY_KIND = NULL, OWNER_ID = NULL, LEASE_EXPIRES_AT = NULL
WHERE PIPELINE_RUN_ID = :row_id AND STATUS = :from_status
AND (OWNER_ID = :owner OR (OWNER_ID IS NULL AND :owner IS NULL))
AND NOT EXISTS (SELECT 1 FROM AUD_PIPELINES_RUN_LOG other
WHERE other.PIPELINE_ID = AUD_PIPELINES_RUN_LOG.PIPELINE_ID
AND other.PIPELINE_RUN_ID <> :row_id AND other.STATUS = 'IN-PROGRESS')
