INSERT INTO AUD_TASK_ATTEMPTS
(TASK_RUN_ID, ATTEMPT_NUMBER, STATUS, QUEUED_AT, REQUESTED_BY, REQUESTED_BY_KIND, LOG_PATH)
SELECT :row_id, COALESCE(MAX(ATTEMPT_NUMBER), 0) + 1, 'QUEUED', :now, :actor, :actor_kind, :log_path
FROM AUD_TASK_ATTEMPTS WHERE TASK_RUN_ID = :row_id
RETURNING ATTEMPT_ID AS attempt_id
