INSERT INTO AUD_TASK_RUN_LOG (TASK_ID, PIPELINE_RUN_ID, STATUS, ATTEMPT_COUNT)
SELECT :task_id, :pipeline_run_id, 'IN-PROGRESS', 0
FROM CFG_TASKS task JOIN AUD_PIPELINES_RUN_LOG run ON task.PIPELINE_ID = run.PIPELINE_ID
WHERE task.TASK_ID = :task_id AND run.PIPELINE_RUN_ID = :pipeline_run_id
AND run.STATUS = 'IN-PROGRESS'
RETURNING TASK_RUN_ID AS task_run_id
