UPDATE AUD_TASK_RUN_LOG SET
STATUS = CASE WHEN a.STATUS IN ('QUEUED','CLAIMED','RUNNING') THEN 'IN-PROGRESS'
WHEN a.STATUS IN ('LOST','TIMED_OUT') THEN 'FAILED' ELSE a.STATUS END,
ATTEMPT_COUNT = a.ATTEMPT_NUMBER, START_DATE = COALESCE(a.STARTED_AT, a.CLAIMED_AT, a.QUEUED_AT),
END_DATE = a.ENDED_AT, SOURCE_COUNT = a.SOURCE_COUNT, TARGET_COUNT = a.TARGET_COUNT,
INSERT_COUNT = a.INSERT_COUNT, UPDATE_COUNT = a.UPDATE_COUNT, DELETE_COUNT = a.DELETE_COUNT,
ROWS_WRITTEN = a.ROWS_WRITTEN, ERROR_MESSAGE = a.ERROR_MESSAGE, TASK_LOG = a.TASK_LOG
FROM AUD_TASK_ATTEMPTS a WHERE a.ATTEMPT_ID = :row_id
AND AUD_TASK_RUN_LOG.TASK_RUN_ID = a.TASK_RUN_ID
AND NOT EXISTS (SELECT 1 FROM AUD_TASK_ATTEMPTS newer
WHERE newer.TASK_RUN_ID = a.TASK_RUN_ID AND newer.ATTEMPT_NUMBER > a.ATTEMPT_NUMBER)
