UPDATE AUD_PIPELINES_RUN_LOG SET STATUS = :status, END_DATE = :now,
ENDED_BY = :actor, ENDED_BY_KIND = :actor_kind,
SLA_STATUS = COALESCE(SLA_STATUS, :sla_status)
WHERE PIPELINE_RUN_ID = :row_id AND STATUS IN ('QUEUED','IN-PROGRESS') AND (OWNER_ID = :owner OR (OWNER_ID IS NULL AND :owner IS NULL))
