-- Start another attempt on :task_run_id: count it and clear the last attempt's results.
UPDATE AUD_TASK_RUN_LOG
SET ATTEMPT_COUNT = ATTEMPT_COUNT + 1, START_DATE = :now, END_DATE = NULL,
    STATUS = 'IN-PROGRESS', ERROR_MESSAGE = NULL, TASK_LOG = NULL,
    SOURCE_COUNT = NULL, TARGET_COUNT = NULL, INSERT_COUNT = NULL,
    UPDATE_COUNT = NULL, DELETE_COUNT = NULL, ROWS_WRITTEN = NULL
WHERE TASK_RUN_ID = :task_run_id

AND NOT EXISTS (SELECT 1 FROM AUD_TASK_ATTEMPTS a WHERE a.TASK_RUN_ID = :task_run_id AND a.STATUS IN ('QUEUED','CLAIMED','RUNNING'))
RETURNING ATTEMPT_COUNT AS attempt_count
