INSERT INTO AUD_TASK_ATTEMPTS
(TASK_RUN_ID, ATTEMPT_NUMBER, STATUS, QUEUED_AT, REQUESTED_BY, REQUESTED_BY_KIND, LOG_PATH, NOT_BEFORE)
SELECT TASK_RUN_ID, ATTEMPT_COUNT, 'QUEUED', :now, :actor, :actor_kind, :log_path, :not_before
FROM AUD_TASK_RUN_LOG WHERE TASK_RUN_ID = :row_id
RETURNING ATTEMPT_ID AS attempt_id
